### ISSUE TITLE
Incorrect highlighting of options in Quiz Template. 

### ISSUE THREAD

**Issue by yatna** [BuildmLearn/BuildmLearn-Toolkit-Android#10]
If a question is there whose correct option in option 2 , then 2nd option is highlighted , however if the same question is edited and the correct option is changed to 3, then instead of highlighting 3rd option , both 2 and 3 are highlighted as shown below.
![screenshot_2016-01-06-03-16-55](https://cloud.githubusercontent.com/assets/8321130/12129198/033de61a-b428-11e5-9df2-a0834ad8eee9.png)

**Comment by opticod** [comment]
Fixed by #149
