### ISSUE TITLE
Menuinflator list increases with each time selecting menu option

### ISSUE THREAD

**Issue by shuklank** [BuildmLearn/BuildmLearn-Toolkit-Android#110]
![screenshot_2016-03-10-01-19-24 1](https://cloud.githubusercontent.com/assets/14854536/13648635/ab97bd22-e65f-11e5-8f7f-a260ff8d7968.png)

**Comment by shuklank** [comment]
In TemplateEditor.java
 `public boolean onPrepareOptionsMenu(Menu menu) {
        Log.d(TAG, "onPrepareOptionsMenu");
        if (showTemplateSelectedMenu) {
            getMenuInflater().inflate(R.menu.menu_template_item_selected, menu);
        } else {
            getMenuInflater().inflate(R.menu.menu_template_editor, menu);
        }
        return true;
    }`
onPrepareOptionsMenu is called everytime when menu opens hence menulist increases everytime.

**Comment by shreyas29** [comment]
This issue is already mentioned #23.
