### ISSUE TITLE
Missing "My Drafts"

### ISSUE THREAD

**Issue by scopeInfinity** [BuildmLearn/BuildmLearn-Toolkit-Android#113]

**Comment by scopeInfinity** [comment]
Segment related with _My Drafts_ : [code](https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/blob/master/source-code/app/src/main/java/org/buildmlearn/toolkit/model/Section.java#L25)

**Comment by opticod** [comment]
closed via #114
