### ISSUE TITLE
Missing drawable resource file

### ISSUE THREAD

**Issue by NezSpencer** [BuildmLearn/BuildmLearn-Toolkit-Android#119]
I just cloned this project today and on building, I got this error: 

![screenshot from 2016-03-14 17 50 33](https://cloud.githubusercontent.com/assets/11639214/13752143/a2612b92-ea0d-11e5-8d57-7cfd8956549d.png)

I opened the layout file and removed the line where this drawable resource was referenced, then it built successfully. I think the person that added this resource forgot to add it to git

**Comment by opticod** [comment]
Fixed
