### ISSUE TITLE
Hint not shown in Flash Template

### ISSUE THREAD

**Issue by yatna** [BuildmLearn/BuildmLearn-Toolkit-Android#12]
The user is prompted to enter a Answer Hint in adding a card in Flash Template.

![screenshot_2016-01-08-01-31-59](https://cloud.githubusercontent.com/assets/8321130/12181462/59dd7608-b5a8-11e5-8d05-5b8af0a70e25.png)

However while running the application in the emulator the hint is not shown anywhere to the user.Nor there is any option to view the Answer Hint.

**Comment by debbarmaonit** [comment]
Can I work on this issue? Please.

**Comment by opticod** [comment]
Merged through #21
