### ISSUE TITLE
Bug in Speech Rate of Spelling Template Simulator

### ISSUE THREAD

**Issue by thegenuinegourav** [BuildmLearn/BuildmLearn-Toolkit-Android#128]
![screenshot_2016-03-18-11-56-58](https://cloud.githubusercontent.com/assets/16540657/13870046/e0fb521a-ed00-11e5-97e1-f5d7d265c8b6.png)
![screenshot_2016-03-18-11-57-05](https://cloud.githubusercontent.com/assets/16540657/13870051/e9f2b7dc-ed00-11e5-8202-b9d5fe15ae7a.png)

In both case, Speech Rate is same

**Comment by scopeInfinity** [comment]
Check Issue #93

**Comment by opticod** [comment]
Added via 7eca22f
