### ISSUE TITLE
Initial text missing in showing Question  in Flash Template .

### ISSUE THREAD

**Issue by yatna** [BuildmLearn/BuildmLearn-Toolkit-Android#13]
During running the application in the  emulator , the left part of the text entered in the question edittext is not shown. Eg if the user entered "Question", then in emulator the user sees it as "uestion".
![screenshot_2016-01-08-01-31-32](https://cloud.githubusercontent.com/assets/8321130/12181584/231fe762-b5a9-11e5-801a-6dc40a9a1696.png)

**Comment by opticod** [comment]
Fixed in current build
