### ISSUE TITLE
Bug in OverFlow Menu of each template

### ISSUE THREAD

**Issue by thegenuinegourav** [BuildmLearn/BuildmLearn-Toolkit-Android#130]
On each click, options in overflow menu increase

![screenshot_2016-03-17-17-12-51](https://cloud.githubusercontent.com/assets/16540657/13871080/9c365560-ed07-11e5-8903-d094224b787d.png)

![screenshot_2016-03-17-17-13-00](https://cloud.githubusercontent.com/assets/16540657/13871087/a35dea38-ed07-11e5-8195-61f5b308b241.png)

![screenshot_2016-03-17-17-13-07](https://cloud.githubusercontent.com/assets/16540657/13871096/ae28562e-ed07-11e5-8e1b-763a6059ff2f.png)

![screenshot_2016-03-17-17-13-14](https://cloud.githubusercontent.com/assets/16540657/13871099/b762a366-ed07-11e5-8063-ff27569a593d.png)

![screenshot_2016-03-17-17-12-29](https://cloud.githubusercontent.com/assets/16540657/13871105/c0f63014-ed07-11e5-80ad-66f49a774acd.png)

**Comment by shreyas29** [comment]
Check Issue #24

**Comment by scopeInfinity** [comment]
@gourav96suri This issue is fixed and already merged in `bug-fixes` branch. I would suggest to checkout fo `bug-fixes` branch. It's currently 12 commits ahead of master

**Comment by gourav96suri** [comment]
OK Thnks man for such a nice advice! @scopeInfinity
