### ISSUE TITLE
Back button not working in Slider Menu.

### ISSUE THREAD

**Issue by yatna** [BuildmLearn/BuildmLearn-Toolkit-Android#14]
If we are in an activity from the slider menu, say "Saved Projects". 
![screenshot_2016-01-08-01-44-00](https://cloud.githubusercontent.com/assets/8321130/12181853/aaf9dfd4-b5aa-11e5-83a2-d1ccc09c2b47.png)

Then clicking on the back button at the bottom does not take back the user to the Home screen of the application, rather it closes the application (keeps it running in the background)

**Comment by debbarmaonit** [comment]
Can I work on this issue, please? It will be somewhat easy for me.

**Comment by opticod** [comment]
@debbarmaonit you can proceed as #74 doesn't meet the goal probably. Fix only one issue in a single PR.
