### ISSUE TITLE
Multiple Selection Implementation in Saved Project

### ISSUE THREAD

**Issue by scopeInfinity** [BuildmLearn/BuildmLearn-Toolkit-Android#142]
Multiple Selection can be for cleaning all projects, except few live projects.

![Multiple Selection](https://cloud.githubusercontent.com/assets/9819066/14409484/0c2a0ea2-ff32-11e5-80e4-1603b01d1e91.gif)

**Comment by iit2014086** [comment]
is anyone working on this?

**Comment by opticod** [comment]
Closed via #163
