### ISSUE TITLE
Replacing existing afollestad's dialogs with dialogs from android support library

### ISSUE THREAD

**Issue by opticod** [BuildmLearn/BuildmLearn-Toolkit-Android#165]
This will reduce the apk size and dependencies on a third-party libraries. 

Need to replace these : In  `build.gradle (Module:app)`
`compile('com.github.afollestad.material-dialogs:core:0.8.5.3@aar') {
        transitive = true
    }
    compile('com.github.afollestad.material-dialogs:commons:0.8.5.3@aar') {
        transitive = true
    }`

Help: https://developer.android.com/guide/topics/ui/dialogs.html

**Comment by ishaan1995** [comment]
Hey , I would really live to work on this enhancement.I am still not sure that would I be able to implement the change as per your coding guidelines and architecture.So could you guide me a little about that?
Thanks
Ishaan

**Comment by opticod** [comment]
Here is one example : 

https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/blob/master/source-code/app/src/main/java/org/buildmlearn/toolkit/templates/InfoTemplate.java#L110-L138

We need to replace this with native dialogs fragments i.e. without using MaterialDialog classes from  ```com.github.afollestad.material-dialogs:core:0.8.5.3@aar```
Here are some nice tutorials: 
- https://guides.codepath.com/android/Using-DialogFragment
- https://developer.android.com/guide/topics/ui/dialogs.html

**Comment by ishaan1995** [comment]
Hey I have created a pull request with the above changes as asked.
https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/pull/174

**Comment by opticod** [comment]
Closed via b24af77
