### ISSUE TITLE
Edit button on Flash Template creates new flash card instead of editing the prior one

### ISSUE THREAD

**Issue by yatna** [BuildmLearn/BuildmLearn-Toolkit-Android#17]
In the flash template if a card is selected for editing by clicking the edit button , a new screen is opened. Suppose in this new screen the question field is changed from "ques1" to "ques" and the ADD button is clicked. Then instead of changing in the same card a new card is created with the question field as "ques".
Initial card:
![screenshot_2016-01-13-23-40-15](https://cloud.githubusercontent.com/assets/8321130/12304038/9461f47a-ba53-11e5-8c82-979a771dbfa4.png)

After editing:
![screenshot_2016-01-13-23-39-48](https://cloud.githubusercontent.com/assets/8321130/12304056/a6909818-ba53-11e5-88e8-b1a66d321359.png)

Whereas, what should be expected is that the same card must be edited by changing its question field from ":ques1" to "ques".

**Comment by batraabhishek** [comment]
+1 for reporting this :) @yatna

**Comment by opticod** [comment]
Fixed via 	ed6c9da
