### ISSUE TITLE
Share Feature on the DraftFragment not working.

### ISSUE THREAD

**Issue by octacode** [BuildmLearn/BuildmLearn-Toolkit-Android#171]
Here's a link to the video depicting the error.
[https://youtu.be/MeTELpfsPBo](https://youtu.be/MeTELpfsPBo)

**Comment by octacode** [comment]
The link is not working directly. You can copy and paste the URL on the address bar. It will work then.
Thanks

**Comment by opticod** [comment]
You can proceed to fix it. 

And the syntax of markdown links are like:  [Video/Image/WebSite](https://youtu.be/MeTELpfsPBo)

**Comment by octacode** [comment]
Great! I am on it.

**Comment by opticod** [comment]
We can remove the share button from it.

**Comment by octacode** [comment]
Okay! Should I proceed to do the changes??...Thanks

**Comment by opticod** [comment]
yes, you can. 👍

**Comment by octacode** [comment]
Okay! Can I proceed to do so? Thanks

**Comment by opticod** [comment]
Closed via #183

**Comment by octacode** [comment]
Thanks for the merge.
