### ISSUE TITLE
Issues with Restore Project feature in Settings fragment.

### ISSUE THREAD

**Issue by octacode** [BuildmLearn/BuildmLearn-Toolkit-Android#175]
[https://m.youtube.com/watch?v=3APV-BkYS9c](https://m.youtube.com/watch?v=3APV-BkYS9c)

App crashes when any directory other than apk made by Toolkit is restored from the Settings fragment.

I have embedded a video depicting the same.

Thanks

**Comment by opticod** [comment]
I was not able to duplicate the issue in my device. Can you please provide the debug log messages. And if it exists, you can proceed to fix it.

**Comment by octacode** [comment]
[https://gist.github.com/octacode/26259f63fe47cb322571b749984f62e2](https://gist.github.com/octacode/26259f63fe47cb322571b749984f62e2)
Here's the gist snippet of the log.

**Comment by octacode** [comment]
Hey! @opticod I have made a PR regarding this issue. Please have a look at it.

**Comment by opticod** [comment]
Thanks @octacode , we will be merging the PRs after reviewing shortly.

**Comment by vishwesh3** [comment]
@octacode Are you still working on this? I would like to work on this.

**Comment by opticod** [comment]
Closed via #266
