### ISSUE TITLE
Making delete operation asynchronous

### ISSUE THREAD

**Issue by opticod** [BuildmLearn/BuildmLearn-Toolkit-Android#176]
If, the size of temporary files are large then `Delete Temporary Files` operation in `Settings Fragment` may block the UI thread. So to avoid this, we can place the operation in `AsynTask`.

**Comment by smart-sachin** [comment]
@opticod Hey, I will like to work on this if anybody's not working.Thanks.

**Comment by opticod** [comment]
you can proceed, @codingblazer

**Comment by octacode** [comment]
@opticod 
Hey! 
I have made a PR #178 regarding this issue. Please have a look at it.
Thanks.

**Comment by codingblazer** [comment]
@octacode Hey, Please inform before taking any issue. It save others time who have already started working.

**Comment by croozeus** [comment]
Guys, please assign the issue to yourself before working on an issue. So that others can know.

**Comment by octacode** [comment]
I will make sure of it next time.

**Comment by opticod** [comment]
Closed via #184
