### ISSUE TITLE
Impossible to delete an existing project from the Saved Projects list.

### ISSUE THREAD

**Issue by yatna** [BuildmLearn/BuildmLearn-Toolkit-Android#18]
The Saved Projects option on the slider menu gives a list of all the projects created in order of date of creation/modification. We can click on a project to edit it and then save it.
However a project cannot be deleted from the Saved Project list i.e. once a project is created it remains on the list forever and there is not an option for the user to delete outdated projects from the list.

**Comment by opticod** [comment]
Added
