### ISSUE TITLE
Pressing back button should open home fragment

### ISSUE THREAD

**Issue by chiragw15** [BuildmLearn/BuildmLearn-Toolkit-Android#180]
Right now, when we press back button, we go to the last fragment opened. So, suppose if someone has opened a fragment 7 times , he has to press back button 7 times to go back to the home fragment. It will be better if we just press back button only once to go to the home fragment.

**Comment by opticod** [comment]
Will I assign you?

**Comment by chiragw15** [comment]
@opticod  yes sure :)

**Comment by free4murad** [comment]
Can I make a PR for this issue?

**Comment by opticod** [comment]
Closed via #206
