### ISSUE TITLE
Reducing the dependencies on third-party libraries

### ISSUE THREAD

**Issue by octacode** [BuildmLearn/BuildmLearn-Toolkit-Android#181]
We can replace these dependencies 
In:`build.gradle (Module:app)` 

`compile 'com.daimajia.easing:library:1.0.1@aar'`
 `compile 'com.daimajia.androidanimations:library:1.1.3@aar'`
with default Android animations. This will reduce the apk size too.

If you find this issue relevant enough. Can I proceed to fix it. 
@croozeus 
@opticod

**Comment by opticod** [comment]
yes u can proceed :+1: @octacode

**Comment by octacode** [comment]
Great! I am on it.

**Comment by opticod** [comment]
Merged via #185

**Comment by octacode** [comment]
Thanks for the Merge.
