### ISSUE TITLE
Supporting TTS in Local Languages + Project Name flexibility

### ISSUE THREAD

**Issue by opticod** [BuildmLearn/BuildmLearn-Toolkit-Android#188]
1. TTS not working for Hindi as mentioned in #179 
2. Flexibility of `Project Name` and`Author Name` in local languages.

**Comment by octacode** [comment]
@opticod 
Hey! I would like to work on this issue.
Thanks

**Comment by octacode** [comment]
@opticod 
There is something I need to ask before I proceed further.
Google Locale Engine doesn't supports Hindi. What should be done. Should I use a Third Party Engine. If yes? Please Suggest me Which engine I should use.
Thanks.

**Comment by opticod** [comment]
Not the current issue, will be opened once other localisation supports are added.
