### ISSUE TITLE
Material Design Issue

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/BuildmLearn-Toolkit-Android#189]
1. While navigating in navigation bar ,Toolbar title remains same as application name but it should be the name of fragment we are in. ( however it changes for "About BuildmLearn" section/activity)
2. Keylines are not followed as per Material Design specs as shown below.

![Expected](https://cloud.githubusercontent.com/assets/13872065/19815595/3ef9cfc0-9d61-11e6-8e22-f98814882e47.png)

![Actual](https://cloud.githubusercontent.com/assets/13872065/19815988/02666ae4-9d63-11e6-8f0a-bc1f0abfa255.jpg)

Can I work on these if it seems fine. Thanks.

**Comment by chiragw15** [comment]
@codingblazer actually while solving issue #180, I realized this issue and solved it too. I'll soon be sending a PR for this. Sorry for trouble.

**Comment by codingblazer** [comment]
@chiragw15 No problem.Thanks for informing me.

**Comment by opticod** [comment]
Closed via #206
