### ISSUE TITLE
Replacing complex navigation drawer with a simpler one.

### ISSUE THREAD

**Issue by chiragw15** [BuildmLearn/BuildmLearn-Toolkit-Android#190]
The code for navigation drawer is too complex, which can easily be replaced by navigation drawer from support library. We then won't be needing files like NavigationDrawerFragment.java, NavigationDrawerMenuAdapter.java, Section.java, fragment_navigation_drawer.xml. 
I already have done 70% of the work and will be sending a PR soon.

**Comment by opticod** [comment]
Closed via #206
