### ISSUE TITLE
Critical Bug in Multiple Selection

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/BuildmLearn-Toolkit-Android#194]
Hey @croozeus @opticod , there is a critical bug in LoadProject Fragment and LoadApkFragment in multiselection. App crashes in both LoadProjectFragment and LoadApkFragment for these features - Unselect All ,Delete Selected. I have depicted the bug in following video and it can be generated in same way as in video. #162 #142 #163 #164 

Video Link - https://youtu.be/S4GIf8usuiI

**Comment by codingblazer** [comment]
Hey @opticod , I am making a pull request for the issue. Please review it. Thanks.

**Comment by opticod** [comment]
Merged via #195
