### ISSUE TITLE
Multiselection Deletion and Unselect All in DraftFragment

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/BuildmLearn-Toolkit-Android#196]
Currently , multiselection deletion and unselect all operation are not implemented in the DraftFragment while they are implemented in other fragments.

**Comment by codingblazer** [comment]
Hey @opticod , Can I work on this if it is intended enhancement ?
Thanks.

**Comment by opticod** [comment]
yaa sure

**Comment by opticod** [comment]
Closed via #200
