### ISSUE TITLE
Old Project deletes without warning (Bug)

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/BuildmLearn-Toolkit-Android#201]
If user makes a new template with  name same as some existing template (in Saved Projects) , it deletes the existing(old) template. It can lead to complete loss of user's existing project without warning.
Video - https://youtu.be/KKlJ2CQUAuQ

@croozeus @opticod What are your views regarding this ? We can implement any of following to solve this -
1. Allow user to create same name template yet preserving the old template.(This  will need adding Timestamp to path of file).
2. Giving a warning to user to reenter a different template name (alert dialog).
3. Warn user of existing template and ask different name through dialog also.
2nd option is standard way and seems best to me. Please tell what way I can work on.Thanks.

**Comment by codingblazer** [comment]
Bug Overview -
The Bug is because currently file path is obtained using the the template title and thus templates that are named same will have exactly same file path. In project, we have used "StreamResult" class of IO for XML transformer which always replaces the old file by new one. It can solved by any of above mentioned ways.

**Comment by opticod** [comment]
I too feel that 2nd option is the natural one.

**Comment by codingblazer** [comment]
@opticod Great ! Will be sending a PR soon.

**Comment by opticod** [comment]
Closed via #202
