### ISSUE TITLE
Need to update screenshots in "How to" activity.

### ISSUE THREAD

**Issue by chiragw15** [BuildmLearn/BuildmLearn-Toolkit-Android#208]
The Screenshots of app in "How to" activity are old, which needs to be updated.

**Comment by opticod** [comment]
You can proceed. @chiragw15

**Comment by opticod** [comment]
@chiragw15, Are you still working on this?

**Comment by chiragw15** [comment]
Actually, I was working on #212 .But, since this issue should be resolved before December release. I'll work on this one first. Will send a PR soon. :)

**Comment by opticod** [comment]
Closed via #252
