### ISSUE TITLE
Author not getting displayed in project and APK Fragment

### ISSUE THREAD

**Issue by chiragw15** [BuildmLearn/BuildmLearn-Toolkit-Android#209]
Author not getting displayed in project and APK Fragment.

![screenshot_20161103-054840](https://cloud.githubusercontent.com/assets/16978820/19952276/1038d168-a18a-11e6-91f8-8b7972998829.png)

**Comment by croozeus** [comment]
I think the string should be replaced with,
"Author Name, 2 Nov 2016"

(Where the Author Name is the actual name of the author)

**Comment by chiragw15** [comment]
@croozeus Okay, So instead of " Modified: 2 Nov 2016, Author: XYZ ", it should be " XYZ, 2 Nov 2016" ?

**Comment by croozeus** [comment]
Yes, that's correct.

**Comment by chiragw15** [comment]
Sure :+1:

**Comment by opticod** [comment]
Closed via #215
