### ISSUE TITLE
Splash Missing

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/BuildmLearn-Toolkit-Android#211]
Currently , there is no splash screen in our app and we instead see a grey screen due to app initialization as shown in the gif.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/13872065/19959169/a5ab3976-a1ca-11e6-8026-a40675bee3c7.gif)

We can replace the grey screen by below splash.This splash will be shown for time exactly the same as time taken by app to initialize (grey screen).

![image](https://cloud.githubusercontent.com/assets/13872065/19959177/b0f0b52c-a1ca-11e6-9459-d19c3cb9c4a1.png)

This is a good practice as recommended by very own Chris Stewart in this article - [BigNerdRanch](https://www.bignerdranch.com/blog/splash-screens-the-right-way/).

**Comment by codingblazer** [comment]
@opticod @croozeus Can I proceed if it's intended enhancement ?

**Comment by opticod** [comment]
@croozeus Presently, all template apps have splash screen but the toolkit 's splash screen is only enabled for first time run to take the author name as input.

**Comment by croozeus** [comment]
@opticod ah, yes! It would be a good idea to add the splash screen on subsequent launches as well then. @codingblazer do you want to take this up?

**Comment by codingblazer** [comment]
@croozeus Yeah sure !.Should I implement fixed time splash or splash with time exactly as time required for app initialization(black screen).

**Comment by opticod** [comment]
Hey! how are you going to calculate the time required to app initialisation? Is it possible to calculate for all devices and all environments for each startups and apply it for the same startup?

**Comment by opticod** [comment]
Or are you going to display the splash screen without having any timer and the effect will be mimicked automatically ?

**Comment by codingblazer** [comment]
Its actually done using theme as explained in this article by Chris - [Big Nerd ranch](https://www.bignerdranch.com/blog/splash-screens-the-right-way/)

**Comment by opticod** [comment]
Its same as my approach asked in 2nd question. 
You can proceed. Make the layout looks like the old one with Edit text removed in normal startup. 

@croozeus Is the design fine or want to modify it :) !
![screenshot_20161109-003047](https://cloud.githubusercontent.com/assets/13851773/20112858/f20070a0-a613-11e6-8c0a-e594458a6cf5.png)

**Comment by codingblazer** [comment]
@opticod Yeah sure. Was just confirming. :-)
Will be sending a PR soon.

**Comment by croozeus** [comment]
@opticod the design looks fine, EditText for name should be removed. 

@codingblazer this splash should be shown for initialisation time. The approach mentioned in the article you shared seems to be the correct one.

**Comment by codingblazer** [comment]
@croozeus Great ! Please assign me.

**Comment by saketkumar95** [comment]
Can i work on this?

**Comment by opticod** [comment]
@saketkumar95 , @codingblazer is already working on this. Feel free to take anyother unassigned issues.

**Comment by opticod** [comment]
Merged via d7f0fbd5882075d5c39aed0454d8d68fcd2f71f5 and fa3dc90c9e2031c565cda7d41d6b06b60a88230e
