### ISSUE TITLE
Validations at various fields in project

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/BuildmLearn-Toolkit-Android#216]
Currently, user can do following -
1.Go to Settings and enter empty string as name.Also user can give " " (space as name) which looks like following.
2.At many other places like in Template name,Author name etc user can give space as name.For ex -
![device-2016-11-06-075846](https://cloud.githubusercontent.com/assets/13872065/20034945/5291cdde-a3f7-11e6-999c-a62af4321a8b.png)
![device-2016-11-06-080052](https://cloud.githubusercontent.com/assets/13872065/20034952/6b7eda6c-a3f7-11e6-9d56-3138cda8ef0c.png)

Expected - These fields must not be empty and must start with alphanumeric character.

**Comment by codingblazer** [comment]
Hey @opticod ,I am making PR regarding this.

**Comment by opticod** [comment]
Closed via #217 & 39f605a & #253
