### ISSUE TITLE
No Code for deleting Temp

### ISSUE THREAD

**Issue by kunall17** [BuildmLearn/BuildmLearn-Toolkit-Android#22]
No Code for deleting Temporary Files!
Link: https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/blob/ab6caf5e6fc1e9f26c9fedf3cf4d7624e0284395/source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/SettingsFragment.java#L23-L26

**Comment by kunall17** [comment]
Fixed here 10a04b4

**Comment by opticod** [comment]
Closed via #72
