### ISSUE TITLE
Add a button to skip tutorials.

### ISSUE THREAD

**Issue by free4murad** [BuildmLearn/BuildmLearn-Toolkit-Android#224]
When the user installs the app and enter his name, he is taken to the TutorialActivity. On tutorial activity he has to browse six pages to go to the last tutorial where he can click on a button which takes the user to HomeActivity.

There should be a button on the first page of TutorialActivity to skip tutorials and go directly to HomeActivity.

**Comment by free4murad** [comment]
Should I make a PR for this.

**Comment by opticod** [comment]
@free4murad Can you provide a demo screen shot of your proposed idea ?

**Comment by free4murad** [comment]
Sure

Currently on installation when the user enter his name and goes to Tutorial activity the activity looks like this
![before](https://cloud.githubusercontent.com/assets/17262180/20238597/11560538-a915-11e6-874c-38984c125f50.png)

What i suggest is that we add a button so that user can skip the tutorials(This feature can be found in most of the apps these days.)

![after](https://cloud.githubusercontent.com/assets/17262180/20238602/2b0da468-a915-11e6-9fac-698bf1e1e1fd.png)

**Comment by free4murad** [comment]
@opticod 
Should i make PR for this.

**Comment by opticod** [comment]
yes

**Comment by saketkumar95** [comment]
Can i work on it? if it's open.

**Comment by free4murad** [comment]
@saketkumar95 
I am working on it.

**Comment by opticod** [comment]
@free4murad , I checked your PR #238,  ```skip buttons``` will be there in all the slides for first time. You had added it for only first slide. Please fix it.

**Comment by opticod** [comment]
Closed via #238 & #248
