### ISSUE TITLE
Share button not working in DraftFragment.java

### ISSUE THREAD

**Issue by free4murad** [BuildmLearn/BuildmLearn-Toolkit-Android#225]
The share button on the toolbar in DraftFragment is not working.

Expected - On pressing the share button user should be able to share the draft.

**Comment by free4murad** [comment]
Should I make a PR for this.

**Comment by opticod** [comment]
Its already fixed through issue #171. Check the **bug-fixes** branch for latest code.

**Comment by free4murad** [comment]
Sorry, I am new to GitHub.

**Comment by opticod** [comment]
No Problem.
