### ISSUE TITLE
Show SnackBar after deleting item with a button to UNDO delete.

### ISSUE THREAD

**Issue by vishwesh3** [BuildmLearn/BuildmLearn-Toolkit-Android#226]
When the user delete the item by mistake or he/she is in confusion whether he/she kept this item or delete it and suddenly he/she thought to kept that item, so for such case there should be a UNDO option, to restore items.

**Comment by vishwesh3** [comment]
@opticod Should I make a PR for this?

**Comment by free4murad** [comment]
@vishwesh3 
Suggestion - 
Implementing SnackBar is a great idea.
Usually the apps that use a SnackBar (gmail etc) don't use a delete confirmation dialog box. I this particular app the delete confirmation dialog box is used almost everywhere.

I think that, if the project mentors give a go ahead to SnackBar idea, you should remove the delete confirmation dialog box. (Actually I, myself thought about this.)
Best of luck.

**Comment by vishwesh3** [comment]
@opticod  your review?

**Comment by opticod** [comment]
@vishwesh3 :+1: you can proceed. @free4murad is right. You can remove the delete confirmation dialog box and implement snackbar like that in gmail .

**Comment by vishwesh3** [comment]
Created PR #234 .

**Comment by vishwesh3** [comment]
Hi, I am facing a got related issue. Actually I forked original repo and commited the changes there, but now I can't submit a PR as the original repo is changed. What shall I do now?

**Comment by opticod** [comment]
Try to rebase your current repo with original repo.

**Comment by vishwesh3** [comment]
Created PR #243

**Comment by opticod** [comment]
Closed via #243

**Comment by vishwesh3** [comment]
In #243 I have done changes in **TemplateEditor.java**  https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/pull/243/files But they are gone after @codingblazer commit (https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/commit/79e79e45abcdca952c9cce0c3c60e8f2469b4c85)
Now again AlertDialog is appearing instead of SnackBar.
@opticod Please have a look on it.

**Comment by opticod** [comment]
@vishwesh3, make a PR to bug-fixes branch ASAP, you can take the help from https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/commit/79e79e45abcdca952c9cce0c3c60e8f2469b4c85#diff-ce9d81d677f8f2cd571e426685cae96a

**Comment by vishwesh3** [comment]
Created PR #300 @opticod please have a look on it.

**Comment by opticod** [comment]
Closed via #300
