### ISSUE TITLE
Edit Item Dialog should have Save button instead of Add

### ISSUE THREAD

**Issue by vishwesh3** [BuildmLearn/BuildmLearn-Toolkit-Android#228]
@croozeus @opticod 
In the **Basic mLearning**, **Learn Spellings**, **Quiz Template** After adding item and clicking on **Edit** icon Dialog appears with **Add** button, it should come **Save** button.
![screenshot_20161113-191423](https://cloud.githubusercontent.com/assets/18511177/20383678/c0fd9b6c-acd6-11e6-83e9-96f50e712818.jpg)

**Comment by vishwesh3** [comment]
Should I create PR?

**Comment by opticod** [comment]
Did u checked the latest build of **bug-fixes** branch?

**Comment by vishwesh3** [comment]
yes, checked. this issue still exits.

**Comment by opticod** [comment]
Check this one https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/commit/b24af7709f316fc6bd61f07e6015634ebe80d458

**Comment by vishwesh3** [comment]
Sorry, I am new to all this. Will make sure all this before creating new issue. Thanks
