### ISSUE TITLE
Menu shows Save Template option two times

### ISSUE THREAD

**Issue by shreyas29** [BuildmLearn/BuildmLearn-Toolkit-Android#23]
In every template, the menu shows "Save Template" option two times. It should show "Save Template" option only one time.

![screenshot_2016-02-02-14-46-27 1](https://cloud.githubusercontent.com/assets/16454030/12744839/7c96e166-c9bc-11e5-8515-e2c40167d129.png)

**Comment by opticod** [comment]
Closed via 9b14e69
