### ISSUE TITLE
Travis is failing

### ISSUE THREAD

**Issue by opticod** [BuildmLearn/BuildmLearn-Toolkit-Android#235]
Travis is failing(#211). 
Here is the log : `The command "echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI" failed and exited with 1 during .`

https://travis-ci.org/BuildmLearn/BuildmLearn-Toolkit-Android

**Comment by croozeus** [comment]
I see that you are trying to tweak the YML file to get this working. However, it may be worth checking that merging which PR exactly broke travis and analyse if any build / project settings got changed in that PR.

**Comment by opticod** [comment]
Regarding merging of PRs, i doubt any one of them broke it.

Build is failing may be due to Google renaming the ABIs again. It has been described in this issue: https://github.com/OneBusAway/onebusaway-android/issues/720#issuecomment-263402921

**Comment by opticod** [comment]
All should rebase their current PRs with current **bug-fixes** branch, if they are sill failing.

Closed via #236

**Comment by croozeus** [comment]
Great, thanks for the quick fix @opticod
