### ISSUE TITLE
Simulate and Save Template options are added in menu list every time setting button is pressed

### ISSUE THREAD

**Issue by shreyas29** [BuildmLearn/BuildmLearn-Toolkit-Android#24]
When First time setting button is pressed.
![screenshot_2016-01-24-12-56-21 1](https://cloud.githubusercontent.com/assets/16454030/12745395/0299ff62-c9bf-11e5-8780-47e89bde19f4.png)

After setting button is pressed for the second time "Simulate" and "Save Template" options are added in the menu options.
![screenshot_2016-02-02-14-56-33 1](https://cloud.githubusercontent.com/assets/16454030/12745291/8e2e6adc-c9be-11e5-8c4f-5dfaf3658766.png)

After setting button is pressed for third time "Simulate" and "Save Template" options are added again in the menu options.
![screenshot_2016-01-24-12-56-46 1](https://cloud.githubusercontent.com/assets/16454030/12745425/2c5da0a6-c9bf-11e5-877a-e6df1d67be0f.png)

Thus every time the setting button is pressed, menu size increases by two options ("Simulate" and "Save template").

**Comment by opticod** [comment]
Closed via 9b14e69
