### ISSUE TITLE
Keyboard covers EditText

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/BuildmLearn-Toolkit-Android#240]
In FirstRunActivity, and keyboard covers the name edittext if opened second time as shown below -

![key](https://cloud.githubusercontent.com/assets/13872065/20756888/66f2545a-b73a-11e6-884a-75b702f47877.gif)

This is a  bug in Android - 
View (Name EditText here) doesn't lifts up when keyboard opens **if** keyboard is coming over any view containing android:gravity="center_horizontal" or android:gravity="center" as attribute.

**Comment by codingblazer** [comment]
@opticod @croozeus I am sending a PR regarding this. Please take a look. Thanks.

**Comment by opticod** [comment]
Closed via  #242
