### ISSUE TITLE
Improve onBackPressesed in TemplateEditor.java.

### ISSUE THREAD

**Issue by m-murad** [BuildmLearn/BuildmLearn-Toolkit-Android#245]
Currently - In TemplateEditor activity if the user presses back button draft is automatically saved (or not if no data is present).
or 
In TemplateEditor activity if the user presses back button saved project is saved as a draft

What should happen - If user presses back button a dialog box asking user if he/she wants to save the existing project/drafts or not should appear.

**Comment by free4murad** [comment]
@opticod 
Should I make a PR for this.

**Comment by opticod** [comment]
@free4murad, you can proceed

**Comment by opticod** [comment]
@free4murad And if the template is fresh and no changes have been made, no need of displaying user that "Unable to perform action: No data". Also fix all such corner through your PR.

**Comment by free4murad** [comment]
@opticod 
I am improving the saveProject and saveDraft function also.

I am doing the following.
1. If the template is a new one and user presses back a dialog box will ask the user if the project should be saved as draft or project file.
2. If the template is an old project file then on back press project will be updated.
3. If the template is a draft then on back press the draft will be updated.

Is that fine?

**Comment by opticod** [comment]
For 1. Add the option of discard also.
For 2. Fine
For 3. Fine
Along with it if the template is fresh and no changes have been made, no need of displaying user that "Unable to perform action: No data" as mentioned in my last message.

**Comment by opticod** [comment]
It looks like it require more testing and need to fill every corner cases. So removing this from DEC-2016 release for now. 
@free4murad

**Comment by free4murad** [comment]
@opticode 
How much time do I have. Actually I have to take my semester test tomorrow.
If I send a PR after that can you include it in Dec, 2016 release. 
Or should I send a PR today.

**Comment by opticod** [comment]
@free4murad,
We  had earlier planned to freeze a version by last Sunday, but as still some issues are open, we planned to give a couple of more days. So, by today or tomorrow, we will be updating our master branch and move on to phase of testing. 

I would suggest you to prepare for your school semester now, as they are also valuable. 
We can merge your PR, once you are done.
