### ISSUE TITLE
Make template selector page more informative

### ISSUE THREAD

**Issue by vishwesh3** [BuildmLearn/BuildmLearn-Toolkit-Android#247]
As of now if template description is long it not able to fit in the space in the card. As shown in the image below.
![buildmlearn select template](https://cloud.githubusercontent.com/assets/18511177/20866265/3f34df60-ba4f-11e6-996c-5f71f455c204.jpeg)

**Better option**
Add a button "Details" and on click of it dialog will open containing all its details. As shown below.
Also `ellipsize="end" ` (Black dots)
![buildmlearn select template_sloved](https://cloud.githubusercontent.com/assets/18511177/20866277/8ee284f4-ba4f-11e6-88fd-5cc42d7257bf.jpg)

I would like to work on this.

**Comment by free4murad** [comment]
@vishwesh3 
On my device its working fine. You might be using a device with small screen. 
You might want to work on changing text size depending on device size.

**Comment by vishwesh3** [comment]
@free4murad I am using phone with 5.5 inch screen display also app should looks good on all the devices .  And to display long description (Full and informative ) we can't always reduce font size to fit in card or `height:wrap_content` of card (which will make card height to wrap its content which will eventually not looks good).  Better way is in the issue.
@opticod Please review it.

**Comment by free4murad** [comment]
@vishwesh3 
That's what I'm saying. We need to make changes so that the app is compatible with small displays.

**Comment by vishwesh3** [comment]
@opticod Should I create PR?

**Comment by opticod** [comment]
Showing them through a dialog on pressing details, is not a good solution. Need to find a better solution.

**Comment by sm86** [comment]
Can I add a scrollbar for the text field and make it scrollable instead?

**Comment by opticod** [comment]
Adding scrollbar in card layout is not a good idea. Adding another UI for smaller screens looks a possible solution now.

**Comment by opticod** [comment]
Closed via #420
