### ISSUE TITLE
[December 2016 Release] Launching app to playstore

### ISSUE THREAD

**Issue by opticod** [BuildmLearn/BuildmLearn-Toolkit-Android#249]
All contributors who are working on various issues are requested to complete them fast as we will be launching our next update to Google PlayStore. :tada:

**Comment by free4murad** [comment]
How much time do we have?

**Comment by croozeus** [comment]
Plan is to freeze a build by Sunday (11 December), test for a week and then release to Play store. 
So essentially anything that is merged by this weekend would go into the build and undergo testing.

**Comment by opticod** [comment]
@croozeus , Thanks for mentioning it. I have labelled some of the open-issues. Shall we give localisation support(#169) in this release?

**Comment by croozeus** [comment]
@opticod Localization support - we can differ to one of the future release.

**Comment by codingblazer** [comment]
@opticod Till when the testing will be done. I wanted to test app properly but am not able to because of exams.

**Comment by opticod** [comment]
@codingblazer, testing will be performed by this weekend.

**Comment by opticod** [comment]
Master branch is now updated and contains the stable version of the code. All can download the APK from https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/releases/tag/v2.5.0 

Test it and report if any issue exists.

**Comment by opticod** [comment]
With some fixes and addition of new crashlytics api key, master branch is updated again and contains the latest stable code version. All can download the APK from https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/releases/tag/v2.5.0

Test it and report if any critical issue exists. We are looking forward to launch an update to playstore soon.

**Comment by opticod** [comment]
Released :tada: 
Get it here: https://play.google.com/store/apps/details?id=org.buildmlearn.toolkit
