### ISSUE TITLE
Multiple Item selected in Navigation bar

### ISSUE THREAD

**Issue by ani27** [BuildmLearn/BuildmLearn-Toolkit-Android#251]
Currently, when you exit app from an page, example >>settings<< and open it again, there are multiple items selected in navigation bar.
![screenshot_20161206-154659](https://cloud.githubusercontent.com/assets/10931958/20921856/0243a734-bbcc-11e6-9dd5-f57cffb51525.png)

I would like to work on this issue.

**Comment by free4murad** [comment]
@ani27 
what version of app are you running.
I am facing no such problem.
Also your navigation drawer is different.

**Comment by ani27** [comment]
@free4murad  the one on the playstore. Isnt that updated?
