### ISSUE TITLE
App Crashes for Match and Comprehension Template  

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/BuildmLearn-Toolkit-Android#254]
@opticod @croozeus While creating a new project, if we choose Match or comprehension template ->Add Meta Details -> Add 2 items -> Now delete Meta details -> Try saving project now -> App crashes.

**Comment by codingblazer** [comment]
The problem is that we have not performed any check on this (if user have provided meta data or not ). It should be provided by user in every case before allowing to save project or user will be asked for the same.
@opticod I am sending a PR for this. Please check.

**Comment by opticod** [comment]
Closed via #258
