### ISSUE TITLE
Backpress should deselect selected items if any.

### ISSUE THREAD

**Issue by free4murad** [BuildmLearn/BuildmLearn-Toolkit-Android#255]
Currently - In "Saved Projects", "Saved APKs" and "My Drafts" if the user has selected items and presses back button the user is taken to the last open fragment.

Intended - User presses back button, if there are any items selected they should be deselected. After that if the user presses back key last fragment (preferably "Home" fragment) should open

**Comment by free4murad** [comment]
@opticod @croozeus 
Should I make a PR to solve this?

**Comment by opticod** [comment]
@free4murad, Fix this before Dec Release

**Comment by opticod** [comment]
@free4murad, Are you working on this?

**Comment by free4murad** [comment]
@opticod 
Yes, I will make a PR soon.

**Comment by opticod** [comment]
Closed via #295
