### ISSUE TITLE
Improve search in "Saved Projects" and "Saved APKs" menu.

### ISSUE THREAD

**Issue by free4murad** [BuildmLearn/BuildmLearn-Toolkit-Android#257]
If the user has save a project or apk by the name "Test VI" and searches the file by entering "VI" the result is not shown. Basicly the current function checks if the project or APK name starts with the search phase.

Intended - Even if the user enter a part of the filename, the file should be shown in search result.

**Comment by free4murad** [comment]
@opticod @croozeus 
Should I make a PR for this issue.

**Comment by opticod** [comment]
Closed via #261
