### ISSUE TITLE
Reducing Apk Size

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/BuildmLearn-Toolkit-Android#262]
Apk size can be reduced significantly before publishing the app -

1. Removing unused activities and files, unused import statements, unused Resources -

- arrays.xml

- 7 unused imports in DictationTemp, FirstRunActivity, FlashTemp, MatchTemp, SettingsFrag.

-  unused resources in strings.xml , dimen.xml etc.

2. Optimizing Drawables (responsible for major apk size)

- There are many drawables of **sharp** which can be implemented using vector drawables. For example -
<img src="https://cloud.githubusercontent.com/assets/13872065/21076592/58af78a0-bf55-11e6-870e-7cf13c9e8e9a.png" />
<img src="https://cloud.githubusercontent.com/assets/13872065/21076593/5c534c7a-bf55-11e6-879a-502361297fca.png"/>
<img src="https://cloud.githubusercontent.com/assets/13872065/21076594/5fc6b964-bf55-11e6-964e-141749b98379.png"/>

- The remaining ones which are not sharp( vector drawable not suitable) we can use tools like pngcrush.com or tinypng.com to decrease size significantly. For example -
![bg_card](https://cloud.githubusercontent.com/assets/13872065/21076617/f6b41a74-bf55-11e6-924d-e913c55d8df4.jpg)

This reduces to more than half size with no noticeable quality change -

![bg_card](https://cloud.githubusercontent.com/assets/13872065/21076618/f87efcd4-bf55-11e6-949a-893884862f86.jpg)

3. Removing External Dependency -

- We can remove this Tutorial dependency by our own Viewpager with indicating dots (NO change in UI) 
`compile 'com.viewpagerindicator:library:2.4.1@aar'`

-We can remove many other unused dependencies like -
 
   `compile` files('libs/core-1.51.0.0.jar')
    compile files('libs/prov-1.51.0.0.jar')
    compile files('libs/zipio-lib-1.8.jar')
    compile files('libs/zipsigner-lib-1.17.jar')
    compile files('libs/zipsigner-lib-optional-1.16.jar')
    compile files('libs/pkix-1.51.0.0.jar')
    compile files('libs/kellinwood-logging-android-1.4.jar')
    compile files('libs/kellinwood-logging-lib-1.1.jar')
    compile files('libs/kellinwood-logging-log4j-1.0.jar')
    compile files('libs/axml.jar') ``

Build works fine after removing them which means they are not been used anywhere in project.
I will not remove dependencies like crashlytics or test related.

@opticod @croozeus Should I proceed ?

**Comment by opticod** [comment]
Yaa proceed. 
For 3. Remove them cautiously with clean rebuild, bcoz one such example is ```axml.jar``` is necessary for decompiling compiled XML and vice versa.

**Comment by codingblazer** [comment]
@opticod Should I create different PR's for 1,2,3 because with so many files changed they can't be differentiated and they are also unrelated to each other.

**Comment by opticod** [comment]
Yaa fell free to create it . @codingblazer

**Comment by codingblazer** [comment]
@opticod I think axml.jar dependency is not in use anymore because its building fine after removing this and running on device too. I have also tried after doing "Clean Project" and and uninstalling app. Its use must have been removed by someone.

**Comment by opticod** [comment]
AxmlReader.class from axml is used in https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/blob/master/source-code/app/src/main/java/org/buildmlearn/toolkit/utilities/SignerThread.java#L112 . So it should not be removed. Please check it very cautiously as removing it may crash the app later.

**Comment by opticod** [comment]
@codingblazer Remove first ```
    compile fileTree(include: ['*.jar'], dir: 'libs')``` then try to remove each.

**Comment by opticod** [comment]
Closed via #283 #284 #285 5cbae12
