### ISSUE TITLE
In flash card template when we start simulator the toolbar says learn spellings.

### ISSUE THREAD

**Issue by free4murad** [BuildmLearn/BuildmLearn-Toolkit-Android#269]
![screenshot_20161212-134449](https://cloud.githubusercontent.com/assets/17262180/21092225/1d71dee6-c071-11e6-95b7-a4c2f47d6cf9.png)

This bug is at some other places as well.

**Comment by free4murad** [comment]
@opticod 
Should I make a PR.

**Comment by opticod** [comment]
Closed via #270
