### ISSUE TITLE
Edit option in Flash Template creates new question

### ISSUE THREAD

**Issue by shreyas29** [BuildmLearn/BuildmLearn-Toolkit-Android#27]
Let's say I have added a question in Flash Template as follows:

![screenshot_2016-02-08-17-35-37 1](https://cloud.githubusercontent.com/assets/16454030/12945907/a42f7552-d016-11e5-9f5e-e0bb7e12954b.png)

Now I want to modify the answer from "ans" to "ans_modified". Instead of making changes in the same question, a new question is created.

![screenshot_2016-02-08-17-36-13 1](https://cloud.githubusercontent.com/assets/16454030/12945962/f4e1a9ac-d016-11e5-94e5-435de6df263f.png)

**Comment by opticod** [comment]
Closed via 	f63c511
