### ISSUE TITLE
App is crashing

### ISSUE THREAD

**Issue by vishwesh3** [BuildmLearn/BuildmLearn-Toolkit-Android#271]
![videotogif_2016 12 12_14 21 19](https://cloud.githubusercontent.com/assets/18511177/21093206/974c4ecc-c076-11e6-8469-f343ab3a001d.gif)
In **My Drafts** page when we select one item (by long pressing) and then click on **Select all** in actionbar app crashes.

**Comment by codingblazer** [comment]
@vishwesh3 I can't replicate this problem. Can you tell the reason or logcat for this problem.
I think you must have some old drafts and in any run from Android Studio data would have been removed causing crash on NullPointerException. (It has happened to me many times on other projects).If this is the case, it  happens only on developer's  device.

**Comment by vishwesh3** [comment]
@codingblazer Yes it was due to some old drafts, as soon as i reinstalled app it was solved. But the app is going to be published on play store soon so I think there should be null pointer check before getting child.

`mListView.getChildAt(i)`

waiting for @opticod review.

**Comment by opticod** [comment]
I too was unable to duplicate the issue. Closing it for now.

**Comment by vishwesh3** [comment]
I got some clue when app is crashing
**Steps to reproduce it**
If the list of draft is more ( list becomes scrollable ) e.g. if your screen can occupy 7 items and you have more than 10 drafts, on selecting all, it crashes.

![videotogif_2016 12 15_16 51 59](https://cloud.githubusercontent.com/assets/18511177/21222533/5430ccb6-c2e8-11e6-9a58-f3e889ad7e62.gif)
![videotogif_2016 12 15_16 48 10](https://cloud.githubusercontent.com/assets/18511177/21222544/5c2080b0-c2e8-11e6-8551-f3f0b2a33a06.gif)


@opticod please have a look on it.

**Comment by opticod** [comment]
@vishwesh3, thanks for it. Its crashing. Re-opened issue. Are you working on this?

**Comment by vishwesh3** [comment]
Yes I am working on it. Please review #300 so that my new commit doesn't go in that PR.

**Comment by opticod** [comment]
Work independently in different branches, will merge them independently.

**Comment by vishwesh3** [comment]
ok. I am almost done will soon create new PR in bug-fixes branch.

**Comment by opticod** [comment]
closed via #309
