### ISSUE TITLE
Show snackbar with UNDO button while deleting saved or draft. 

### ISSUE THREAD

**Issue by vishwesh3** [BuildmLearn/BuildmLearn-Toolkit-Android#272]
**Observed Behaviour**
On deleting dialog is show with confirmation.

**Expected Behaviour**
On successful deletion show snackbar with UNDO button, on click of this undo button deleted projects will be restored.

I would like to work on this, assign me this.

**Comment by opticod** [comment]
According to material design guidelines  https://material.google.com/components/dialogs.html

> Dialogs contain text and UI controls. They retain focus until dismissed or a required action has been taken. Use dialogs sparingly because they are interruptive.
Some dialog types include:
Alerts are urgent interruptions that inform about a situation and require acknowledgement.

Hence, we left them as it is for deleting project, apks or drafts. Whereas we will be using the snackbar deletion procedure for datas in template editor.

**Comment by vishwesh3** [comment]
ok
