### ISSUE TITLE
Author becomes Unknown 

### ISSUE THREAD

**Issue by vishwesh3** [BuildmLearn/BuildmLearn-Toolkit-Android#273]
In **Saved APk** and **Saved projects** wile making search author becomes "Unknown" and date 1 Jan 1970.

![videotogif_2016 12 12_16 08 26](https://cloud.githubusercontent.com/assets/18511177/21096523/4baa6a7a-c086-11e6-8b04-8f86b8ff7f12.gif)

**Comment by opticod** [comment]
Yaa fix this quickly.

**Comment by opticod** [comment]
Closed via #275
