### ISSUE TITLE
Issue with Search in SavedProjects and SavedAPKs + My Drafts

### ISSUE THREAD

**Issue by opticod** [BuildmLearn/BuildmLearn-Toolkit-Android#276]
1. While searching if any item is deleted, then on closing the search view, adapter still contains that item.
2. In Drafts, if an item is saved as project and on clicking back, if no drafts exists then, it should display proper empty message.

**Comment by codingblazer** [comment]
@opticod Can I work on it?

**Comment by octacode** [comment]
@codingblazer. You already are on more than 1 issue lemme work on it. ^^

**Comment by opticod** [comment]
Thank you Guys, but i have already fixed it. @codingblazer @octacode

**Comment by codingblazer** [comment]
@opticod Great !! 
@octacode I don't have more than one issue assigned.

**Comment by opticod** [comment]
Closed via #277
