### ISSUE TITLE
Addition of screen transitions.

### ISSUE THREAD

**Issue by octacode** [BuildmLearn/BuildmLearn-Toolkit-Android#281]
Right now, There is no screen transition animation when an intent is called. We can add one of the following transit between screens:-
1. Fade-In , Fade-Out
2. Slide-Left, Slide-Right
No new external decencies will be required for this.
If this is considered enhancement, I would like to work on it.
Thanks

**Comment by octacode** [comment]
@opticod ^

**Comment by opticod** [comment]
We need to first see, which animation looks better in which case.

So can you list the animations you would like to add with which fragment/activity transitions?

**Comment by sm86** [comment]
@octacode are you working on this enhancement?

**Comment by octacode** [comment]
@sm86 yup!

**Comment by octacode** [comment]
@opticod 
I have tried the slidein-left and slide out right transitions and for what I have seen is that they aren't really smooth. So I am thinking of using fade-in and fade out cause they are not just smooth but they fit with the very flow of the app.

**Comment by octacode** [comment]
@opticod
@croozeus 
 As I have noticed in apps like Whatsapp, there's a common screen transition for all the intent changes.
I too want to do the same to the Toolkit. I have tried the default android transitions provided and I find fade_in and fade_out really consistent both in terms of performance and visuality. So I am making the PR for the same.
Any Suggestions?

**Comment by opticod** [comment]
Thanks @octacode, our team will review this and merge it shortly.

**Comment by opticod** [comment]
Closed via #398
