### ISSUE TITLE
Change the textfield lables throughout the project.

### ISSUE THREAD

**Issue by m-murad** [BuildmLearn/BuildmLearn-Toolkit-Android#286]
![screenshot_20161213-052311](https://cloud.githubusercontent.com/assets/17262180/21121934/357633b4-c0f5-11e6-979e-4000f6ebbc7a.png)
"Add meta details". User will not understand metadata.
![screenshot_20161213-052240](https://cloud.githubusercontent.com/assets/17262180/21121935/36787222-c0f5-11e6-95b9-ebb9fee79339.png)
Instead of "Template Name" we should use "Project Name".
![screenshot_20161213-052400](https://cloud.githubusercontent.com/assets/17262180/21121936/3758221e-c0f5-11e6-980a-bc951f0ec9fe.png)
Here edit text hint should be "Question" not Name.

Similar issues can be seen throughout the project.

**Comment by free4murad** [comment]
@opticod 
Should I make a PR for this.

**Comment by sm86** [comment]
Can I make a PR for the same?

**Comment by free4murad** [comment]
@sm86 
I have done the coding part,
Just waiting for the approval of project maintainers.

**Comment by opticod** [comment]
Ok, create the PR and also attach some screenshots to it.

**Comment by opticod** [comment]
@free4murad "Template name" is fine, what are you suggesting for "meta details"?
Hints can be changed from "Name" to "Question"
