### ISSUE TITLE
In the first run activity the name should appear in center.

### ISSUE THREAD

**Issue by free4murad** [BuildmLearn/BuildmLearn-Toolkit-Android#298]
![screenshot_20161214-023035](https://cloud.githubusercontent.com/assets/17262180/21159086/cfa2c03c-c1a5-11e6-87e7-fd09037123be.png)

**Comment by opticod** [comment]
Closing as already discussed in https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/pull/242
