### ISSUE TITLE
File Path is not automatically included when sharing through gmail

### ISSUE THREAD

**Issue by nikhilchowdary** [BuildmLearn/BuildmLearn-Toolkit-Android#302]
When sharing a project , it is not attached to gmail automatically.This makes  to manually navigate to the "internalstorage/buildmlearn/saved/"   location
 
I will fix will fix this issue and send a pr asap

![screenshot_2016-12-14-18-23-28-229_com google android gm](https://cloud.githubusercontent.com/assets/16875030/21182950/9cd51e62-c22b-11e6-94f1-87e5d7acedf8.png)

**Comment by opticod** [comment]
It seems only with Internal Storage, I tried having External Storage and
it's working fine.
You can proceed.

**Comment by opticod** [comment]
@nikhilchowdary, Are you still working on this issue?

**Comment by nikhilchowdary** [comment]
It's working with internal storage too.I actually didn't accept permission to access media and storage after installing the app
