### ISSUE TITLE
Making first activity full screen.

### ISSUE THREAD

**Issue by free4murad** [BuildmLearn/BuildmLearn-Toolkit-Android#305]
@opticod 
Many apps like Shareit make their launcher activity fullscreen to make it good looking.
We can do the same.

What do you think?

**Comment by shikharbhuddi** [comment]
@free4murad The launcher activity is already fullscreen. @opticod Correct me if I am wrong.

**Comment by opticod** [comment]
@shikharbhuddi, the launcher activity is not currently fullscreen.

@free4murad, Not necessary at this moment.
