### ISSUE TITLE
In Comprehension and Quiz template if the user edits the questions he can make options same.

### ISSUE THREAD

**Issue by free4murad** [BuildmLearn/BuildmLearn-Toolkit-Android#306]
In Comprehension and Quiz template at the time of adding a new question the user cannot make options same, but while editing the question the same can be done.

I am making a PR for this.

**Comment by manish15597** [comment]
can i work on this ... I have a little knowledge on Android

**Comment by free4murad** [comment]
@manish15597
I have already created a PR for this issue.
Watch out for unassigned issues.

**Comment by manish15597** [comment]
okay ... I'm new to this... didn't know what what PR meant ... got it ... ill look out for unassigned issues.

**Comment by free4murad** [comment]
@manish15597 
I suggest that you go through [this](https://github.com/free4murad/Git-Guide) repository so that you can understand the basics of the Git.
Once you are done with this, download the code base, install the app and try to find bugs.

**Comment by manish15597** [comment]
Thanks.

**Comment by opticod** [comment]
Closed via 1161827
