### ISSUE TITLE
Two Toasts upon pressing back for exit

### ISSUE THREAD

**Issue by shikharbhuddi** [BuildmLearn/BuildmLearn-Toolkit-Android#313]
Pressing the back button second time also shows the toast.

**Comment by free4murad** [comment]
@shikharbhuddi 
please write the steps to reproduce the error so that everyone can confirm.

**Comment by shikharbhuddi** [comment]
@opticod @free4murad In the HomeActivity, upon pressing the back button twice to exit, the toast with text "Tap back once more to exit." appears twice. Please confirm.

**Comment by opticod** [comment]
@shikharbhuddi, Yes we should display only one time. Shall I assign this to you?

**Comment by shikharbhuddi** [comment]
@opticod That'd be great!

**Comment by opticod** [comment]
Closed via #318
