### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by vishwesh3** [BuildmLearn/BuildmLearn-Toolkit-Android#315]
**Steps to reproduce**
In Match Template If meta data is deleted and draft is accessed it crashes.

![videotogif_2016 12 20_22 35 10](https://cloud.githubusercontent.com/assets/18511177/21360746/305b6878-c707-11e6-996a-e51b99b24d4e.gif)

**Solution**

- On Deletion meta data delete all data.

- When Draft is accessed check for meta data and manage there.

Somewhat similarly issue persists in Comprehension Template too.

**Steps to reproduce**
In Comprehension Template draft If meta data is not present  and we hit add button (plus) it crashes.
![videotogif_2016 12 20_22 44 46](https://cloud.githubusercontent.com/assets/18511177/21360763/3d16ca76-c707-11e6-8293-66cc31e72226.gif)

@opticod Please review and let me know with which solution should we go or suggest better solution and assign this to me, I would love to work on  this.

**Comment by opticod** [comment]
If I am not wrong, @freemud, is currently working on this issue on #308

**Comment by croozeus** [comment]
If @free4murad is working on this, let's close this issue.

**Comment by opticod** [comment]
#308, is a vast PR updating many things, its not good to merge it without testing much before the December release. Hence fixing it by small fix via de249ef

**Comment by croozeus** [comment]
Ok, great
