### ISSUE TITLE
Integrating Application Crash Report for Android

### ISSUE THREAD

**Issue by shikharbhuddi** [BuildmLearn/BuildmLearn-Toolkit-Android#316]
ACRA is a library enabling Android Application to automatically post their crash reports to a report server.
Considering the frequency of issues related to crashes and erroneous behaviour, we can integrate a crash report tool (ACRA, crashlytics, firebase etc.)
@opticod @codingblazer @free4murad Your opinions.

**Comment by codingblazer** [comment]
@shikharbhuddi I think its already integrated with crashlytics.

**Comment by shikharbhuddi** [comment]
@codingblazer Thanks! Found it in the manifest file.
