### ISSUE TITLE
Tell a friend.

### ISSUE THREAD

**Issue by octacode** [BuildmLearn/BuildmLearn-Toolkit-Android#324]
@opticod 
Like most of the apps we can add a feature of tell a friend in the settings activity. It will launch a shared intent with a suitable message and the playstore link to the app.

**I will work on it**
Thanks

**Comment by opticod** [comment]
Ok. you can continue.

**Comment by octacode** [comment]
@opticod, Thanks for assigning me. I have already made a PR regarding the same. Please have a look at it. #325.
