### ISSUE TITLE
In MatchTemplate all the options can be same.

### ISSUE THREAD

**Issue by free4murad** [BuildmLearn/BuildmLearn-Toolkit-Android#326]
![screenshot_20161223-202837](https://cloud.githubusercontent.com/assets/17262180/21456529/bb1d0d9c-c94e-11e6-823a-0787ae84dcc6.png)

I suggest that every option should be checked for duplicates in both lists.

**Comment by free4murad** [comment]
@opticod 

I am making a PR for this.

**Comment by opticod** [comment]
Great.!

**Comment by opticod** [comment]
Closed via #327
