### ISSUE TITLE
Issue in ComprehensionTemplate and MatchTemplate.

### ISSUE THREAD

**Issue by m-murad** [BuildmLearn/BuildmLearn-Toolkit-Android#329]
If the user deletes meta data in Comprehension or Match template the options are still there.

I suggest that if the user delets meta data the options for that meta data are also deleted.
Because if the user wants to edit the meta he can do so by using button in toolbar, but deleting probably means that he wants to delete the whole question.

**Comment by free4murad** [comment]
@opticod 
I am making a PR for this.

**Comment by opticod** [comment]
No, its not a problem. If user deletes meta data, then the options can exists. Though the project cannot be saved without meta details, and will be asked for it.

**Comment by free4murad** [comment]
@opticod 
What I am trying to say is that if the user wants to edit the meta data he/she has the option to do that. 
But deleting metadata probably means that user wants to delete the complete question. 
Currently - If the user want to delete the complete question he has to first delete the metadata and then all the options individually.
If this is implemented then it becomes easier for user to delete the data.

**Comment by free4murad** [comment]
@opticod 
just let me know if you find its ok to implement this functionality.

**Comment by opticod** [comment]
Ok, it got it now. Then, while deleting the meta data, we can ask the user in dialog box, if he also wants to delete the questions.

**Comment by free4murad** [comment]
@opticod 
I don't think adding a dialog box to delete metadata is a good option.
There are following cases that can arise
1. User wants to edit metadata. (He can do it using edit buttons provided.)
2. User wants to delete the question. (He has to delete all options and then metadata.)

Letting the user just delete the metadata is illogical. He can edit it.
Deleting metadata means he wants to delete complete question.

Anyway, If you still think we should add the dialog box, I will do that.

**Comment by opticod** [comment]
@free4murad, if we don't keep the dialog box, then accidentally an user can loose his/ her all questions, It will be good to confirm from the user before deleting all the questions at a go.
