### ISSUE TITLE
Color of toolbar is not set to its default

### ISSUE THREAD

**Issue by vishwesh3** [BuildmLearn/BuildmLearn-Toolkit-Android#331]
**Steps to reproduce**

- Open **Saved Projects**, **Saved APK's** or **My Drafts**.

- By long pressing select any item.

- Open navigation drawer and move to any other fragment.

**Observed Behaviour**
Color to toolbar doesn't changed to its default.

**Expected Behaviour**
On moving to any any other fragment toolbar color should set to its original color.

![videotogif_2016 12 24_01 40 50](https://cloud.githubusercontent.com/assets/18511177/21462012/62660a3a-c97d-11e6-8f75-2f015ef6af0a.gif)

**Comment by Prem0707** [comment]
@opticod  Can u proceed for it?

**Comment by vishwesh3** [comment]
@Prem0707 I am working on it and waiting for @opticod review for making PR.

**Comment by opticod** [comment]
Thanks @vishwesh3

**Comment by vishwesh3** [comment]
Created PR #332 . :)

**Comment by opticod** [comment]
Closed via #332
