### ISSUE TITLE
App is crashing in older versions of android(like jelly bean)

### ISSUE THREAD

**Issue by iit2014086** [BuildmLearn/BuildmLearn-Toolkit-Android#333]
Steps to reproduce:
create a project using match template
run simulator
click on check answers

(or)

generate apk for match template project
install and run it

@opticod if possible see if this is the same in any other versions of android devices too

**Comment by iit2014086** [comment]
@opticod , any views on this bug? i feel this needs to be included in dec release.

**Comment by opticod** [comment]
Thanks.

**Comment by iit2014086** [comment]
@opticod I have already sent a pr for this. But let's wait for croozeus's review on #310 . Because if that get's mergerd, this issue wont occur.

**Comment by opticod** [comment]
@iit2014086, Merged #334 for time-being. For multiple match the followings as mentioned in #310, Lets wait for @croozeus 's review.
