### ISSUE TITLE
Number of toasts if two or more options are same in Quiz Template

### ISSUE THREAD

**Issue by shikharbhuddi** [BuildmLearn/BuildmLearn-Toolkit-Android#336]
**Steps to reproduce:**
1. Create a Quiz Template.
2. Add a new question with more than one same option as answer.

**Expected Behaviour:**
Toast "Two or more options are same." should appear once.

**Observed Behaviour:**
Multiple Toasts "Two or more options are same."
If number of same options = 2, the observed behaviour is the expected behaviour.
If number of same options = 3, the observed behaviour is not the expected behaviour. (Toasts shows thrice.)
If number of same options = 4, the observed behaviour is not the expected behaviour. (Toast shows six times.)

![g_20161224_1605214](https://cloud.githubusercontent.com/assets/13435742/21466459/2df26462-c9f3-11e6-9212-e99d9cc72fb2.gif)

**Comment by sm86** [comment]
Can I work on this issue?

**Comment by shikharbhuddi** [comment]
@sm86 I am done with the code. Waiting for @opticod to assign it.

**Comment by opticod** [comment]
@shikharbhuddi , great thanks for reporting this.

**Comment by opticod** [comment]
@shikharbhuddi, Are u on this?

**Comment by m-murad** [comment]
@opticod 
If @shikharbhuddi is not working on it should i send a PR?

**Comment by opticod** [comment]
Closed via #373
