### ISSUE TITLE
App crashes on restoring project from apk

### ISSUE THREAD

**Issue by ani27** [BuildmLearn/BuildmLearn-Toolkit-Android#337]
App crashes when I restore some other APK(not one build from BuildmLearn).

![bug](https://cloud.githubusercontent.com/assets/10931958/21471426/0b69bc6a-cad9-11e6-9781-16de65fd2c53.PNG)

Basically it is due to calling dialog box from a background thread.

**Comment by sm86** [comment]
I didn't get it. How did you restore some other APK? Can you provide the steps that lead to this error.

**Comment by octacode** [comment]
@ani27 Are you using the app from Playstore? Because this bug has already been reported and resolved.

**Comment by opticod** [comment]
If its already been fixed, we can close it for now.
