### ISSUE TITLE
Improvement: Added AutoSave Feature

### ISSUE THREAD

**Issue by kunall17** [BuildmLearn/BuildmLearn-Toolkit-Android#34]
Autosave feature to save the newly added items to any project.
In default this feature is enabled, In settings we can disable this feature!

![autosave](https://cloud.githubusercontent.com/assets/12700799/13197162/55aef16c-d80b-11e5-8ffb-5ce473a5b176.gif)

**Comment by opticod** [comment]
Draft Feature Added
