### ISSUE TITLE
Timer doesn't stops in Comprehension 

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/BuildmLearn-Toolkit-Android#342]
When the timer is running and app goes in background ( phone call or home button pressed) the timer is still running and question screen comes up suddenly when timer finishes (maybe while you are on call).
Also, in Comprehension app, if user presses back to exit while timer is running the same problem happens (questions screen appearing suddenly)

**Expected Behavior** -The timer should pause when app goes in background and resume when app comes to foreground.
@opticod Sending a PR for it.

**Comment by opticod** [comment]
Fixed via https://github.com/BuildmLearn/Toolkit-mobile-templates/pull/43 & #343
