### ISSUE TITLE
Single Row in Match Template Illogical

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/BuildmLearn-Toolkit-Android#344]
In match template, we can create single row item. Since this is Matching, after creating app, user gets nothing to match (one entry on left , one on right) and on will always get full score.
In template editor user should be asked to give atleast 2 items.

I have solved this @opticod. Should I send a PR.

**Comment by opticod** [comment]
Ok, @codingblazer sent the PR, my college is going to start again in coming weeks. May get busy in multiple activities, will review them slowly in free time.

**Comment by codingblazer** [comment]
@opticod Np  :-)

**Comment by opticod** [comment]
Closed via #363
