### ISSUE TITLE
No Author name appears in Saved Projects and Saved Apk list

### ISSUE THREAD

**Issue by ani27** [BuildmLearn/BuildmLearn-Toolkit-Android#345]
In saved apk and saved projects, the author name is not there. only **Author :** is there

![screenshot_20161227-174529](https://cloud.githubusercontent.com/assets/10931958/21499532/c46ecdde-cc5c-11e6-87e7-188e91c1fb61.png)

I have solved this bug. Can i send a PR?

**Comment by sm86** [comment]
Did you install the app from Play Store? I think you have an older version of the application.

**Comment by opticod** [comment]
@ani27 , You can download the latest v2.5.0 from playstore. It has been recently updated. To remain always updated for development purposes, you may follow **bug-fixes** branch.

**Comment by ani27** [comment]
@opticod  I was using the build from master branch at the time I posted this issue. Thanks for letting me know my mistake.
