### ISSUE TITLE
Option can't be unselected in Quiz and Comprehension

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/BuildmLearn-Toolkit-Android#346]
In both quiz and Comprehension, at the end we are showing Correct, Wrong and **UNASWERED**. But in questions, once user has selected any radio button, user can't unselect it (can't choose question to be unanswered).
Fix - When we click on already selected radio button in radio group , it can't be unselected. 
So either we can show separate button to clear all selected options OR 
use checkbox OR 
force user to answer every question (i.e. don't show unanswered at end) OR
adopt any of these [SO](http://stackoverflow.com/questions/15836789/android-radio-button-uncheck?rq=1)

**Comment by sm86** [comment]
Can I work on this issue?

**Comment by codingblazer** [comment]
@sm86 Actually I have already started work on this. I am waiting for @opticod opinion on that and will resume work then. Thanks anyway.

**Comment by opticod** [comment]
It's really a good feature to have. You can proceed @codingblazer

**Comment by codingblazer** [comment]
@opticod Which approach you want me to follow. :-)

**Comment by opticod** [comment]
Not checkbox. Add one button, nicely matching positioned in the view. On selecting it, deselect all radio buttons. 
Need to add the fix in simulator and in created APKs. sent the other pr in toolkit-templates repo.

**Comment by codingblazer** [comment]
Yeah button would be good!!

**Comment by opticod** [comment]
Closed via #366
