### ISSUE TITLE
Multiline Template Name

### ISSUE THREAD

**Issue by scopeInfinity** [BuildmLearn/BuildmLearn-Toolkit-Android#35]
![12516730_954104807959799_40966723_o](https://cloud.githubusercontent.com/assets/9819066/13257938/fa26ff6a-da76-11e5-99ec-b5a2d0eafff2.jpg)

![12751885_954104731293140_240845589_o](https://cloud.githubusercontent.com/assets/9819066/13257943/ff6b3e78-da76-11e5-8049-b10d755f13ab.jpg)

**Comment by opticod** [comment]
Fixed
