### ISSUE TITLE
Check for Update : Feature

### ISSUE THREAD

**Issue by dipakkr** [BuildmLearn/BuildmLearn-Toolkit-Android#350]
@opticod @croozeus  As we are heading for release of next update on play store. I think application should have feature to check for update.

**I would like to work on this.**

**Comment by octacode** [comment]
@dipakkr Can you please elaborate what this feature is for or how is it going to work?...

**Comment by dipakkr** [comment]
@octacode simply checking for any update of application on playstore.

**Comment by octacode** [comment]
![screenshot_20161229-142411](https://cloud.githubusercontent.com/assets/20819968/21540087/c51a74be-cdd2-11e6-82e1-8cb5cb726b0c.png).
Like in here, **Check for new version**

**Comment by dipakkr** [comment]
@octacode Yes, but it will be in Settings.I will send a PR soon.

**Comment by opticod** [comment]
Great u can work on it.

**Comment by opticod** [comment]
Closed via #365
