### ISSUE TITLE
ButterKnife Implementation in code : Enhancement 

### ISSUE THREAD

**Issue by dipakkr** [BuildmLearn/BuildmLearn-Toolkit-Android#351]
Using butterknife in application can make our code lot of cleaner. It will also improve the app performance and make views light weight. I think it would be good if we include this in next update of application.

**Any suggestions**  @croozeus @opticod

**Comment by codingblazer** [comment]
@dipakkr 
> It will also improve the app performance and make views light weight.

Though butterknife can be good idea it doesn't increase app performance or make views light weight. :-)

**Comment by opticod** [comment]
@dipakkr , its a really good idea to make the code cleaner and avoid some redundant codes, but from our planned December releases, we are less focusing on using another new library. Adding new libraries also increases APK size. Closing it for now.

**Comment by dipakkr** [comment]
@opticod ok. Yes, i also said this for including in any further release.
