### ISSUE TITLE
Add feature: Rearranging items

### ISSUE THREAD

**Issue by vishwesh3** [BuildmLearn/BuildmLearn-Toolkit-Android#352]
Add a feature to rearrange items in each template. 
For example:- In Comprehension Template or Quiz template if instructor prepare a quiz, once questions are added there is no way to rearrange questions.

**Comment by sm86** [comment]
Similar to issue #349

**Comment by croozeus** [comment]
I checked #349 and it is not exactly what @vishwesh3  is suggesting. @vishwesh3 this looks like a useful feature to work on. Please pick this up if you want to work on this.

**Comment by vishwesh3** [comment]
Thanks @croozeus working on this and will send PR soon.

**Comment by sm86** [comment]
Sorry my mistake. Just understood that.

**Comment by vishwesh3** [comment]
Created PR #383 Please have a look.

**Comment by opticod** [comment]
Closed via #383
