### ISSUE TITLE
In TemplateEditor you we have multiple options to edit or delete items.

### ISSUE THREAD

**Issue by m-murad** [BuildmLearn/BuildmLearn-Toolkit-Android#355]
For some templates the Edit and Delete options are repeated.
One set is with the item and another is in the toolbar.

@opticod we should remove this dublicacy.

**Comment by opticod** [comment]
Yes, you should. While creating the PR, attach some screenshots with it.

**Comment by free4murad** [comment]
@opticod
I have made a PR

Requested screen shots  - 


![screenshot_20170103-163404](https://cloud.githubusercontent.com/assets/17262180/21610596/edfcc1a0-d1ee-11e6-8972-d7e7c99ed580.png)

![screenshot_20170103-163210](https://cloud.githubusercontent.com/assets/17262180/21610597/f4ecb4c0-d1ee-11e6-91d5-c7302d13a778.png)

**Comment by opticod** [comment]
the design looks little weird. Can you update it with some padding following material design guidelines or some new changes?

**Comment by opticod** [comment]
@free4murad, is there update on this?

**Comment by m-murad** [comment]
@opticod 
Sorry i missed this.
Will start woking on it and send a PR in a day or two.

**Comment by m-murad** [comment]
![screenshot_20170209-042716](https://cloud.githubusercontent.com/assets/17262180/22761388/77e023b4-ee80-11e6-8ebb-c8ad1fe320b5.png)
![screenshot_20170209-042741](https://cloud.githubusercontent.com/assets/17262180/22761390/77e40290-ee80-11e6-8754-932ae5f283b7.png)
![screenshot_20170209-042721](https://cloud.githubusercontent.com/assets/17262180/22761389/77e24e82-ee80-11e6-9eb9-6495fd9cdc1d.png)

@opticod 
please take a look.

**Comment by opticod** [comment]
Thanks @free4murad,you can proceed making the PR.
