### ISSUE TITLE
Add feature : Option to install generated apk from the dialog window

### ISSUE THREAD

**Issue by archie94** [BuildmLearn/BuildmLearn-Toolkit-Android#356]
Right now when the apk is generated successfully we have no option but to read the message and dismiss it. Then we go on to install the apk from notification drawer. How about having an option to install the generated apk from the dialog window itself? 

@croozeus @opticod Your thoughts on this?

**Comment by opticod** [comment]
If I am not wrong, we can directly install the created APK by clicking on the notification.

**Comment by archie94** [comment]
Yes, what I am saying is how about installing it directly from the dialog box. That way we do not have to pull down the the notification. 
Only a minor improvement, if at all. :sweat_smile:

**Comment by opticod** [comment]
But that will generate redundancy.

**Comment by archie94** [comment]
Well this is what I had in mind. Note that we will have to remove the notification if user does decide to click on the INSTALL option. Otherwise a notification should remain. 

![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/12955150/21578156/052e3b2e-cf9c-11e6-9267-83fd363d81cd.gif)

Thoughts ?

**Comment by croozeus** [comment]
Based on the feedback of users, the local notification is not very useful. So we can remove this. 

Once the notification is removed we can add the option to install the APK from the dialog. 

@archie94 if you can do both, then feel free to pick this up.

**Comment by opticod** [comment]
Closed via #372

**Comment by opticod** [comment]
@archie94, Reopening, Please redirect your PR to bug-fixes branch.
You can take help from your last PR: https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/pull/372/files

**Comment by opticod** [comment]
Closed via #408
