### ISSUE TITLE
Selecting and unselecting items

### ISSUE THREAD

**Issue by vishwesh3** [BuildmLearn/BuildmLearn-Toolkit-Android#364]
There are some minor issues regarding selecting and unselecting items:-

- On long pressing on items of **Flash Template** item is selected but item background color is not changed. Which will confuse user which item is selected.
![videotogif_2017 01 02_20 08 31](https://cloud.githubusercontent.com/assets/18511177/21594898/11907ee6-d14e-11e6-8001-93dfd6ac9a6e.gif)

- When items are selected and back button is pressed it finishes activity. On back button it should  unselect the items.

- As of now if we want to unselect an item we have to long press on it. I think it would we better to unselect on single click like in whatsapp.

**Comment by taeven** [comment]
can i work on that??

**Comment by vishwesh3** [comment]
@taeven thanks for your interest. I am waiting for @opticod review before making PR.

**Comment by taeven** [comment]
okay!

**Comment by opticod** [comment]
@vishwesh3, Your idea looks fine. You can proceed.

**Comment by opticod** [comment]
Closed via #423
