### ISSUE TITLE
Quiz and Comprehention Template bug.

### ISSUE THREAD

**Issue by free4murad** [BuildmLearn/BuildmLearn-Toolkit-Android#369]
Currently - In quiz and comprehension template if the user has selected option 4 as the correct answer and while editing the question he removes the option text and pressed ok button then option 1 becomes answer. 

Expected - If the user removes the option the it should no longer be marked as correct option. App should ask the user to select a new option.

**Comment by free4murad** [comment]
@opticod @croozeus 
I am making a PR.

**Comment by opticod** [comment]
Thanks @free4murad , for reporting this. You can proceed to creating PR.

**Comment by opticod** [comment]
Closed via #413
