### ISSUE TITLE
Edit Button of Basic mLearning/Learn Spelling Template showing New Item Dialog 

### ISSUE THREAD

**Issue by scopeInfinity** [BuildmLearn/BuildmLearn-Toolkit-Android#37]
Inconsistent code written again in Adapter class of both templates.

On clicking like
![12765807_954248627945417_1491878079_o](https://cloud.githubusercontent.com/assets/9819066/13269222/a10cc910-daac-11e5-910e-850a4bd39c9a.jpg)

This opens up
![12755201_954248797945400_556765730_o](https://cloud.githubusercontent.com/assets/9819066/13269227/a8c7b0fc-daac-11e5-91d3-eb6bccfbbfb9.jpg)

**Comment by croozeus** [comment]
Please clarify what is being fixed here. What do you mean by "Inconsistent code written again in Adapter class of both templates."

**Comment by scopeInfinity** [comment]
In  _source-code/app/src/main/java/org/buildmlearn/toolkit/templates/LearnSpellingAdapter.java_
The Dialog Box Code for Edit Button 
> final MaterialDialog dialog = new MaterialDialog.Builder(mContext)
>                         .title(R.string.info_add_new_title)
>                         .customView(R.layout.info_dialog_add_edit_data, true)
>                         .positiveText(R.string.info_template_add)
>                         .negativeText(R.string.info_template_delete)
>                         .build();

First, for on pressing Edit Button on left side : Dialoge with message Add/Delete pop up. Which is Already Fixed here #30 for _source-code/app/src/main/java/org/buildmlearn/toolkit/templates/LearnSpellingTemplate.java_ 
But still, We are having Add/Delete Dialogue Code in Adapter class. Why are we simply not calling function working fine in _LearnSpellingTemplate.java_ for Reusability.
