### ISSUE TITLE
App crashes in comprehension if time entered is 0.

### ISSUE THREAD

**Issue by free4murad** [BuildmLearn/BuildmLearn-Toolkit-Android#375]
In comprehension template if the user enters time as 0 a toast is shown which says that time cannot be zero.
But if the user enters time as 00 or (0)^* the project is successfully compiled but the generated app crashes.

@opticod @croozeus 
I am making a PR for this.

**Comment by archie94** [comment]
Hi @free4murad , I tried to reproduce this and yes the project is successfully compiled for time as 0(0)* .
Please note that in my case the generated app did not crash but we directly land on the question(s) section.

**Comment by free4murad** [comment]
@archie94 
The simulator is crashing for time 0^0.
The generate app is not crashing but takes you directly to the questions.

**Comment by opticod** [comment]
Closed via #389
