### ISSUE TITLE
Reducing AKP size.

### ISSUE THREAD

**Issue by m-murad** [BuildmLearn/BuildmLearn-Toolkit-Android#377]
We can reduce the APK size by setting `shrinkResources` property to true in build.gradle file of the app.
By using this android studio will not include the unused resources and assets that are not referenced to in the code.

**Comment by free4murad** [comment]
@opticod @croozeus 
I am making a PR for this.

**Comment by opticod** [comment]
Thanks, you can add it . @free4murad

**Comment by tanvidadu** [comment]
@opticod @croozeus  I will like to send the PR for this issue.
