### ISSUE TITLE
App Crash in Saved Projects

### ISSUE THREAD

**Issue by sm86** [BuildmLearn/BuildmLearn-Toolkit-Android#380]
Steps to reproduce:
Long press some project and then click on Select All option and the app crashes. 
Ideally, all the items in the list must be selected.
I would like to fix this issue.

**Comment by vishwesh3** [comment]
@sm86 I can't replicate this issue. Yes before this was issue and was reported in #271 And was resolved in #309. I think your branches are not updated with original ones that's why it is causing problem.

**Comment by sm86** [comment]
@vishwesh3, I saw the issue you stated was in Drafts. The drafts is working exactly fine. But I got the issue in Saved Projects. Please let me know if it is also resolved and there is an issue with my branch

**Comment by vishwesh3** [comment]
Yes https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/pull/309/files in Saved Projects it is solved.
