### ISSUE TITLE
Naming Convention: Enchancement

### ISSUE THREAD

**Issue by sm86** [BuildmLearn/BuildmLearn-Toolkit-Android#381]
After you select any template, you have two text fields, template and author. The user is asked for template name. Instead he should be asked for Project name. 
Our app terminology:
Templates are supposed to be themes like Match, Flash Cards.
We also have saved projects section.

**Comment by free4murad** [comment]
@sm86 
I am already working on this as this issue comes under issue #286

**Comment by sm86** [comment]
So sorry, I am closing the issue
