### ISSUE TITLE
Additional html content in description of Video

### ISSUE THREAD

**Issue by yadav-rahul** [BuildmLearn/BuildmLearn-Toolkit-Android#386]
While editing video in VideoCollection Template, additional html's paragraph opening (`<p>`)  and closing (`</p>`) tag appears in beginning and end of the description.

![giphy](https://cloud.githubusercontent.com/assets/15157620/21745208/03adc12e-d54c-11e6-967f-ead904836a4f.gif)

To avoid this, we can add a method which will trim the description fetched from an url entered.

**Comment by yadav-rahul** [comment]
@opticod @croozeus What are your views on it? Shall I make PR for this?

**Comment by opticod** [comment]
@yadav-rahul, if you remove all of it, then the text will not be formatted in the output. We have added this feature so that user can do some text-formatting.

**Comment by yadav-rahul** [comment]
@opticod OK. I misunderstood it for additional content. Shall I close this issue then?
