### ISSUE TITLE
Delete confirmation dialogue

### ISSUE THREAD

**Issue by taeven** [BuildmLearn/BuildmLearn-Toolkit-Android#391]
In setting, the app doesn't ask confirmation to delete temporary files. I think we should add an alert dialogue for that. I am done with code, making PR for that.
![screenshot_20170114-004251](https://cloud.githubusercontent.com/assets/17789028/21942388/ecd68a70-d9f2-11e6-8c66-79b433b41b87.png)
![screenshot_20170114-004256](https://cloud.githubusercontent.com/assets/17789028/21942389/ece3672c-d9f2-11e6-9b1b-5722fdff0538.png)

**Comment by opticod** [comment]
BTW, don't you think the temporary files are useless? So no need of showing confirmation messages. If user deletes it, then it hardly make any problem.
