### ISSUE TITLE
Change in UI Navigation 

### ISSUE THREAD

**Issue by akmittal006** [BuildmLearn/BuildmLearn-Toolkit-Android#396]
I would like to propose change in ui navigation.
As of now home screen does nothing but show simple screen with "+" fab at bottom.
Instead of idle screen i would like to add **tabs based navigation** for
1.saved APKs
2.drafts
3.Saved projects

As this are most used options in nav drawer.
@opticod  this is not much of a issue, but it will definitely improve user experience.

**Comment by anuradhagupta345** [comment]
@opticod Shall I send PR for this?

**Comment by akmittal006** [comment]
@anuradhagupta345 sorry anuradha m working on it , waiting for @opticod  's confirmation.

**Comment by anuradhagupta345** [comment]
@akmittal006 Can you update your progress on this one?

**Comment by opticod** [comment]
If we are adding tabs based navigation, then need to remove the navigation bar menu. Need to add the Settings in status menu bar...... Please provide some rough implementation, how you will be handling all these. Thanks.

**Comment by akmittal006** [comment]
@opticod  everything will remain same basically same, i will just pull out 
1.saved APKs
2.drafts
3.Saved projects

from navigation drawer to tabs. I think navigation drawer still works fine with tabs.

So user can just swipe between these fragments instead of pulling out nav drawer everytime.

**Comment by opticod** [comment]
@akmittal006  Got u. That will be cool. You can work on this. 

Can you please make some changes in your existing PR https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/pull/402  as mentioned there, so that I can merge it ?

**Comment by akmittal006** [comment]
@opticod sorry for the delay , I had my midterms. I will change it soon.

**Comment by akmittal006** [comment]
@opticod  After making changes, it looks like this. 
![ezgif-3-9b194ddeef](https://cloud.githubusercontent.com/assets/8525715/23902571/a362b962-08e7-11e7-917f-466362779ab3.gif)

**Comment by opticod** [comment]
@akmittal006 Looks nice. We need to include the welcome message somewhere in the app....may be in about section.

@croozeus , can we work on this?

**Comment by akmittal006** [comment]
@opticod I was thinking of displaying that when the saved projects list is empty.
Also there is some commented out code in home fragment(xml file), since home fragment is useless what to do with that code

**Comment by croozeus** [comment]
The icon metaphors are not convincing i.e. a first time user looking at the app will not figure out which tab is for what. Besides, I for one like the first time user to see the welcome message rather than the 3 tabs with empty content. Let's stick to the old approach.
