### ISSUE TITLE
UX wise floating button is not needed on the HomeScreen

### ISSUE THREAD

**Issue by vjs3** [BuildmLearn/BuildmLearn-Toolkit-Android#4]
UX wise the floating button is not a good choice for going to templates.As according to guidelines the plus shaped floating button is not needed to add something in general.I would like to shift functionality of that button to navigation drawer (means shifting option of template to drawer itself) and remove that from home screen.(Remaining application and other floating buttons will be at their same location).

@batraabhishek please review my suggestions so that I can work on that.

**Comment by croozeus** [comment]
FAB is used for primary action on a screen - which in our case is the to create a new template. I would suggest keeping it the way it is and not moving it to the navigation drawer and hiding the primary action.

**Comment by vjs3** [comment]
As we are adding item to existing template not adding any template that's
why I suggested above thing. We are actually adding items inside template
not adding template itself so it would be good if we have FAB inside
template (which is already there).

Closed #4
<https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/issues/4>.

—
Reply to this email directly or view it on GitHub
<https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/issues/4#event-495847959>
.

**Comment by batraabhishek** [comment]
Hey @vjs3, on clicking FAB we are creating a new project based on existing template. Thus as @croozeus said, FAB is acting as primary action similar to creating a new mail fab in gmail app, and upload fab on youtube app. 

Also moving it to Navigation Drawer, will make it less accessible to user. the aim is to create new project in one click.

**Comment by vjs3** [comment]
Ok I got it.Thanks for your clarification :smile:
