### ISSUE TITLE
problem with toasts queue in settings fragment

### ISSUE THREAD

**Issue by nikhilchowdary** [BuildmLearn/BuildmLearn-Toolkit-Android#400]
If the user clicks "Rate Toolkit" button in settings when network is unavailable repeatedly,Then  the number of toasts in the queue increases .If user then clicks  the button "Delete Temporary Files" then the toast displaying ' whether the temporary files were deleted or not ' has to wait until all the  toasts  that are created before  are displayed

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/16875030/22142343/ecbbe3a4-df1b-11e6-9b97-f137bb2c030d.gif)

I am a sending a PR for this

**Comment by opticod** [comment]
Closed via #401
