### ISSUE TITLE
Reformatting the Code

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/BuildmLearn-Toolkit-Android#403]
Currently, most of files in our project are not formatted properly as per coding guidelines. 
@opticod Should I send PR for this ?

**Comment by saketkumar95** [comment]
Already asked here https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/pull/361

**Comment by opticod** [comment]
Most of the files are formatted. Some recent addition of new codes from new contributors may had slightly unformatted it. Will reformat them while merging into master. Closing it now.
