### ISSUE TITLE
application choser dialog opens multiple times for tell a friend and restore project

### ISSUE THREAD

**Issue by nikhilchowdary** [BuildmLearn/BuildmLearn-Toolkit-Android#404]
@opticod @croozeus 
In settings fragment there are two problems:

1 . If the user by mistake clicks "Tell a friend" or "Restore Project" twice.The choser dialog for selecting the application opens twice.This makes the user to close both the dialogs if he doesn't want to choose anything

![tellafriend](https://cloud.githubusercontent.com/assets/16875030/22174641/8e051b20-e009-11e6-9939-771cf51fda98.gif)

2 . The author name length must be limited .Otherwise if the author name  or template name or combination of both of them is large,the emulator doesn't show author name and template name.
If we proceed further the emulator crashes.There is also UI distortion in navigation drawer

  

![capture1](https://cloud.githubusercontent.com/assets/16875030/22174748/a43fb39e-e00b-11e6-88ba-4aececb209f5.PNG)

![capture](https://cloud.githubusercontent.com/assets/16875030/22174706/f788fd22-e00a-11e6-893b-351964ca816e.PNG)

![capture2](https://cloud.githubusercontent.com/assets/16875030/22174735/750a2f3c-e00b-11e6-8d91-6bfbfb6d6dc8.PNG)

After proceeding further in emulator ,it crashes.

I will send a PR for this ASAP

**Comment by opticod** [comment]
Thanks.. @nikhilchowdary

**Comment by opticod** [comment]
Closed via #406
