### ISSUE TITLE
Improvement in the tablet layout

### ISSUE THREAD

**Issue by arp95** [BuildmLearn/BuildmLearn-Toolkit-Android#405]
Using grid layout instead of linear layout when app viewed on tablets for particular section of the app like while displaying of the templates etc.
Can i work on this?

**Comment by anuradhagupta345** [comment]
@opticod Shall I send PR for this?

**Comment by arp95** [comment]
@anuradhagupta345 im working on this. will send a pr in a day.

**Comment by anuradhagupta345** [comment]
@arp95 Can you update your progress on this issue?

**Comment by arp95** [comment]
@anuradhagupta345
have already submitted the pr for the same.

**Comment by opticod** [comment]
Thanks

**Comment by opticod** [comment]
Closed via #409
