### ISSUE TITLE
Adding personalized Keyboard feature

### ISSUE THREAD

**Issue by opticod** [BuildmLearn/BuildmLearn-Toolkit-Android#41]
Currently we have to press back button to hide the soft keyboard,this may be lengthy for users. If we add the feature of hiding the keyboard even when the user clicks away from an input field or tried to scroll ,then it will be more user friendly. Thus increasing usability .

**Comment by debbarmaonit** [comment]
Can someone please assign me to this issue? I would like to work on this.

**Comment by opticod** [comment]
@debbarmaonit , I have already  made a PR for the same.

**Comment by debbarmaonit** [comment]
The issue is OPEN that's why I asked.
