### ISSUE TITLE
next button on first screen after installation

### ISSUE THREAD

**Issue by DravitLochan** [BuildmLearn/BuildmLearn-Toolkit-Android#412]
For the current scenario, when a user downloads the app, or when data is cleared, the first activity asks the user to enter the name. but there is no next button here. the only way to proceed from here is to click on the tick from the keyboard. so I propose to give a next button which takes the user to the tutorial sliders and hence no change in the flow. 
 I'd like to add this thing.

**Comment by DravitLochan** [comment]
@opticod please look into this

**Comment by opticod** [comment]
@DravitLochan, +1 You can proceed. Once you are done with the PR, add a screenshot to it for review.

**Comment by DravitLochan** [comment]
I have added functionality to the button. please review the position for the button. @opticod 
We can also use an ImageButton pointing in the right direction.
cheers!
![screenshot_20170221-024111](https://cloud.githubusercontent.com/assets/14837478/23141952/52b2732c-f7df-11e6-9a3a-1e794bafd949.png)

**Comment by opticod** [comment]
Current position odd, try putting it below the edit-text and aligned centre.

**Comment by opticod** [comment]
Try to make it transparent or some other color combination, which suits the best

**Comment by DravitLochan** [comment]
How about this?
![screenshot_20170221-133011](https://cloud.githubusercontent.com/assets/14837478/23158554/a74b2cf6-f845-11e6-92e8-081b7705c149.png)

**Comment by DravitLochan** [comment]
@opticod  what do you propose?

**Comment by opticod** [comment]
Did you tried with keeping it transparent and same formatting as the `Skip button `in 'How to' or tutorial fragments ? If not, then please try it once, as its good to have the design of the buttons consistent throughout.

**Comment by DravitLochan** [comment]
damn. that looks pretty cool in fact.  
what do you say?
![screenshot_20170221-220416](https://cloud.githubusercontent.com/assets/14837478/23174236/bd2687be-f881-11e6-81a4-05487849f4ac.png)

**Comment by DravitLochan** [comment]
@opticod my last pr was about reducing the gradle time. I think it is still not merged. please give it a merge so that I can pr this. thanks :)

**Comment by DravitLochan** [comment]
@opticod please review and merge the pr for gradle build so that I can proceed with creating a new pr for this issue. The work is done!

**Comment by opticod** [comment]
My semester exam is going on, so its hard to review and merge now. Our team will shortly merge it after reviewing. Thanks for your patience. 

You can work simultaneously in multiple branch and can create PRs from them.

**Comment by DravitLochan** [comment]
sorry! i'll wait for the team to approve. Just as a matter of fact, I have also made that button and following it's screenshot is atached in the issue. i'll pull it under different request. Sorry once again! :)

**Comment by opticod** [comment]
Closed via #433 & 	2c79128
