### ISSUE TITLE
Same matching topics in Match Template

### ISSUE THREAD

**Issue by shikharbhuddi** [BuildmLearn/BuildmLearn-Toolkit-Android#414]
**Steps to reproduce:**

Create a Match Template.
Add a matching topic.
Add the same topic (with same values of Strings) again.

**Expected Behaviour:**
Toast "Two entries cannot be same." should appear and the matching topic should not be added. Even after editing, the check should be done.

![g_20170209_2036026](https://cloud.githubusercontent.com/assets/13435742/22789324/a509ee3c-ef08-11e6-9664-0f77052dc7bc.gif)

**Observed Behaviour:**
Same topics get added.

![g_20170209_2017033](https://cloud.githubusercontent.com/assets/13435742/22789334/ac267960-ef08-11e6-86fa-db8621560900.gif)

**Comment by shikharbhuddi** [comment]
@opticod Please look into it and assign. I can send a PR then.

**Comment by m-murad** [comment]
@shikharbhuddi 
I have solved this issue earlier
Please build the app using latest code.

**Comment by m-murad** [comment]
@shikharbhuddi 
Solved via PR #327

**Comment by shikharbhuddi** [comment]
@free4murad Thanks!

**Comment by opticod** [comment]
@shikharbhuddi Latest codes are merged into bug-fixes branch, so for development purpose refer it.

**Comment by shikharbhuddi** [comment]
@opticod Thanks!
