### ISSUE TITLE
UI Issues in small screen

### ISSUE THREAD

**Issue by rishsethia** [BuildmLearn/BuildmLearn-Toolkit-Android#418]
In small screens , in the template selection activity , the template cardview doesn't render text properly on smaller devices (< 5 inches).
![screenshot_2017-02-10-12-41-02-100_org buildmlearn toolkit](https://cloud.githubusercontent.com/assets/11053890/22818165/a987e160-ef91-11e6-92ab-2d016d747f6b.png)

![screenshot_2017-02-10-12-40-43-796_org buildmlearn toolkit](https://cloud.githubusercontent.com/assets/11053890/22818121/736f25ca-ef91-11e6-88f6-f2f6a4144ce1.png)

I want to fix this behaviour by making the layout parameters  relative instead of fixed , so that it looks good on all screens !

@opticod @croozeus please suggest !

**Comment by codingblazer** [comment]
@rishsethia Making layout relative will not solve the problem for all screen sizes. You will also need to define different screen size buckets and change dimensions for each size bucket proportionally.

**Comment by rishsethia** [comment]
Okay @codingblazer I'll do that ! Should I go ahead with it then ?

**Comment by codingblazer** [comment]
@rishsethia I think you should. But proceed once @opticod approve.

**Comment by opticod** [comment]
@rishsethia We have some discussions in https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/issues/247 . But not sure if anyone already had started working, if not, feel free to assign it to you. 

@vishwesh3 @sm86 , Are you working on #247?

**Comment by opticod** [comment]
Closed via #420
