### ISSUE TITLE
Invalid TemplateName CRASH Application and DELETE project

### ISSUE THREAD

**Issue by scopeInfinity** [BuildmLearn/BuildmLearn-Toolkit-Android#43]
Giving Some of Characters like '/' in Template Name Crash Application on Build APK, and Delete the Saved Project on Clicking 'Save Project'.

![aqua_power_hd_2016-02-24-18-07-45](https://cloud.githubusercontent.com/assets/9819066/13286561/3a904352-db28-11e5-922b-b49075e1bb37.png)

![aqua_power_hd_2016-02-24-18-08-00](https://cloud.githubusercontent.com/assets/9819066/13286562/3d3980a0-db28-11e5-90d7-3fbdcdc3312c.png)

**Comment by opticod** [comment]
Added
