### ISSUE TITLE
Resize the screenshots in the documentation

### ISSUE THREAD

**Issue by Rimjhim28** [BuildmLearn/BuildmLearn-Toolkit-Android#452]
The sizes of sceenshot in documentation can be fixed such that all the screenshots have same widths and heights.

I would like to work on this issue. 
@opticod @croozeus Can I proceed?

**Comment by opticod** [comment]
yes you can proceed. Recently due to some github changes, images are not side by side, please also place the images side by side.

**Comment by Rimjhim28** [comment]
Sure @opticod! Will send a PR shortly.

**Comment by opticod** [comment]
Closed via #453
