### ISSUE TITLE
Deleting Feature of Saved Project Missing

### ISSUE THREAD

**Issue by opticod** [BuildmLearn/BuildmLearn-Toolkit-Android#48]
Currently we have no option available to delete a saved Project.

**Comment by nehaPolo** [comment]
Hey, @opticod How to import the android project in android studio?

**Comment by nehaPolo** [comment]
it is not getting imported by simply using the import project option

**Comment by opticod** [comment]
Hi @nehaPolo , make sure you import or open the `source-code` folder. and after that you have to fix plugin version and sync the project .

Make this changes to build.gradle
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

Hope this helps.
