### ISSUE TITLE
Saved Projects Screen Improvements

### ISSUE THREAD

**Issue by chhavip** [BuildmLearn/BuildmLearn-Toolkit-Android#5]
In my opinion if there are no saved projects, a message should be displayed indicating the user does not have any saved projects yet, and if need be directed to creating a new project option.

**Comment by opticod** [comment]
@chhavip you can proceed. :+1:

**Comment by octacode** [comment]
Hey! I have made a PR regarding this issue. Please have a look at it. :)

**Comment by opticod** [comment]
Closed via #170
