### ISSUE TITLE
Pending Intent Missing for Notifications

### ISSUE THREAD

**Issue by opticod** [BuildmLearn/BuildmLearn-Toolkit-Android#50]
On Clicking the notifications, nothing happens. If we add the feature to open the apk file just created, by clicking the notification, then it will be easier to view the apk.

**Comment by croozeus** [comment]
@opticod I have create a branch for bug-fixes. Can you submit all your fixes to bug-fixes branch?

I can then evaluate and merge them.

**Comment by opticod** [comment]
@croozeus Yea , sure. Please see my new PRs to bug-fixes branch .

**Comment by croozeus** [comment]
Thanks, I merged a few today. Some of them require testing and they will be merged when someone tests them.

It would be great if you could work on some prioritized issues, for example #53  is something I am looking to have a solution for.
