### ISSUE TITLE
Reordering of Question in Template Editor

### ISSUE THREAD

**Issue by scopeInfinity** [BuildmLearn/BuildmLearn-Toolkit-Android#52]

**Comment by croozeus** [comment]
@scopeInfinity Please provide a detailed description of the issue raised. Else we will close this in due time.

**Comment by scopeInfinity** [comment]
This is ordering of my Item in List.
    First Q2 then Q1 and I want to move Q1 upward. i.e. First Q1 the Q2

![aqua_power_hd_2016-02-28-12-24-45](https://cloud.githubusercontent.com/assets/9819066/13377925/5e48efd8-de16-11e5-80f2-fa9b1afb64aa.png)

**Comment by croozeus** [comment]
Thanks for adding the details. I don't think this is required. The newly added item should be visible readily and hence added on the top.

**Comment by scopeInfinity** [comment]
OK

**Comment by scopeInfinity** [comment]
Will it be better in Quiz Template. Since during some quiz ordering of question matters.
Let's say, Answer of third Question depends on Problem solved during Second Question.
