### ISSUE TITLE
Setting up an automated Build System for this project

### ISSUE THREAD

**Issue by croozeus** [BuildmLearn/BuildmLearn-Toolkit-Android#53]
It would be great if we could have a freely available, automated build system that compiles an APK for the project (bug-fixes branch) on each commit and makes it available for download. 

The reason for triggering the compilation on each commit is to know if any pull request that was merged caused a problem.

**Comment by opticod** [comment]
@croozeus , This is really a nice idea. 
We can use the Travis CI - Open Source Edition ( Free ) for compiling the builds for every PR.

**Comment by opticod** [comment]
@croozeus , Have successfully deployed automated build system that compiles the APK whenever any PR occurs or commit is added in my forked repo.: 
Please see it in Readme areas of : https://github.com/opticod/BuildmLearn-Toolkit-Android
Build report at : https://travis-ci.org/opticod/BuildmLearn-Toolkit-Android
Details for PRs will come like this example :
![screenshot from 2016-02-28 20-47-14](https://cloud.githubusercontent.com/assets/13851773/13380018/c18a9bbe-de5c-11e5-9b47-15463b457eb6.png)
 
Travis details : https://travis-ci.org/

**Comment by opticod** [comment]
Added. Closing for now.
