### ISSUE TITLE
Incorrect Highlighting in Quiz Template

### ISSUE THREAD

**Issue by scopeInfinity** [BuildmLearn/BuildmLearn-Toolkit-Android#67]
This Issue was already created,  but now it seems to be deleted.

**Comment by scopeInfinity** [comment]
![aqua_power_hd_2016-02-28-16-37-15](https://cloud.githubusercontent.com/assets/9819066/13378859/03ec2400-de3a-11e5-9f3b-85cf92fc603c.png)

**Comment by croozeus** [comment]
Thanks for adding the issue. Kindly check if the issue exists in bug-fixes branch.

**Comment by scopeInfinity** [comment]
I recently pull bug-fixes. This bug exists there.

**Comment by opticod** [comment]
I checked, its fixed. Closing this Issue.
