### ISSUE TITLE
Two Items Selected in Navigation Drawer

### ISSUE THREAD

**Issue by scopeInfinity** [BuildmLearn/BuildmLearn-Toolkit-Android#70]
Bug only for front-end.

To replicate bug
> Open BuildmLearn Application
> Open Navigation Drawer
> Goto Settings/Saved Projects
> Press Back Button (Application Minimized)
> Open BuildmLearn Again
> Check Navigation Drawer

It auto-selects `Home` without resetting previous Selection.

![aqua_power_hd_2016-02-28-18-12-00](https://cloud.githubusercontent.com/assets/9819066/13379442/eb590478-de4b-11e5-9cdf-1c19f8881902.png)

**Comment by opticod** [comment]
Merged #71 . Thanks.
