### ISSUE TITLE
Live Change of Username 

### ISSUE THREAD

**Issue by scopeInfinity** [BuildmLearn/BuildmLearn-Toolkit-Android#75]
Let's say I change username from Settings.
It won't get updated on View until I open Settings again.
It won't get updated on TextView in Navigation Drawer until I restart app again.
![screenshot from 2016-02-28 23 13 17](https://cloud.githubusercontent.com/assets/9819066/13380846/7c510ec8-de72-11e5-9865-1fb0d9186268.png)

**Comment by opticod** [comment]
closed via Merged #76
