### ISSUE TITLE
Share Project Feature

### ISSUE THREAD

**Issue by scopeInfinity** [BuildmLearn/BuildmLearn-Toolkit-Android#83]
We currently have `Share APK` option but no option for Sharing Project i.e. project-name.buildmlearn file sharing. It can be common case when multiple users are adding items in template editor one-by-one.

**Comment by opticod** [comment]
It will be convenient and best to have that option in "Saved Projects" fragment.

**Comment by opticod** [comment]
Modified the last code to make share feature available both at ```template editor``` and ```load project fragment```

**Comment by opticod** [comment]
Fixed
