### ISSUE TITLE
Bug in Simulator Learn Spelling Result

### ISSUE THREAD

**Issue by scopeInfinity** [BuildmLearn/BuildmLearn-Toolkit-Android#87]
Data of previous current test on simulator is not reset  by clicking on `Exit` on Back Press.
Thus giving wrong results.

![Screenshot](https://cloud.githubusercontent.com/assets/9819066/13418305/26db4a8e-df9a-11e5-86d6-973d9631ecf7.png)

**Comment by opticod** [comment]
closed via #88
