### ISSUE TITLE
Delete Button not working in Add new item dialog box in Flash Template

### ISSUE THREAD

**Issue by yatna** [BuildmLearn/BuildmLearn-Toolkit-Android#9]
Whenever a card is long pressed for editing in Flash Template the following Dialog Box is opened.
However, the delete button here does not delete the card. It just closes the dialog box.
![screenshot_2016-01-06-03-31-43](https://cloud.githubusercontent.com/assets/8321130/12129033/1b0ec6f2-b427-11e5-8768-47c3a73102f8.png)

**Comment by opticod** [comment]
Fixed by #30, Thanks @yatna @shreyas29
