### ISSUE TITLE
Cant load project on android studio

### ISSUE THREAD

**Issue by naveenshukla** [BuildmLearn/BuildmLearn-Toolkit-Android#96]
While loading project on my pc in android studio. I am getting following error : 
"Gradle Project refresh failed 
Error : connection refused"

**Comment by mayank-kgp** [comment]
Hi....
Are you working on proxy?

**Comment by shuklank** [comment]
Yeah I am working on proxy  and I am adding proxy too to gradle.properties but still I am getting this problem

**Comment by prasang7** [comment]
Do you have '_ExernalSystemException_' in event log, where is says unable to save?

**Comment by championswimmer** [comment]
Possibly due to this 
https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/issues/104

**Comment by shuklank** [comment]
Yes @championswimmer

**Comment by opticod** [comment]
Fixed
