### ISSUE TITLE
Special Template Name generating apk with Unexpected Name

### ISSUE THREAD

**Issue by scopeInfinity** [BuildmLearn/BuildmLearn-Toolkit-Android#97]
Giving `.*buildmlearn.*` type of Template name will generate apk by replacing `buildmlearn` with `apk` text.

![aqua_power_hd_2016-03-02-22-31-40](https://cloud.githubusercontent.com/assets/9819066/13468072/0519bc0e-e0c7-11e5-9771-73a1c4c13013.png)

**Comment by opticod** [comment]
closed via #98
